//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAuth2.Localizations {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OAuth2.Localizations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   OAuth2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string APP_TITLE {
            get {
                return ResourceManager.GetString("APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLIENTFORM_BUTTON_ADD {
            get {
                return ResourceManager.GetString("CLIENTFORM_BUTTON_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLIENTFORM_BUTTON_APPLY {
            get {
                return ResourceManager.GetString("CLIENTFORM_BUTTON_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLIENTFORM_BUTTON_REMOVE {
            get {
                return ResourceManager.GetString("CLIENTFORM_BUTTON_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redirect URIs과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLIENTFORM_REDIRECT_URIS {
            get {
                return ResourceManager.GetString("CLIENTFORM_REDIRECT_URIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NAME과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLIENTS_CLIENT_NAME_LABEL {
            get {
                return ResourceManager.GetString("CLIENTS_CLIENT_NAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SUB과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLIENTS_CLIENT_SUB_LABEL {
            get {
                return ResourceManager.GetString("CLIENTS_CLIENT_SUB_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLIENTS_CLIENT_TYPE_LABEL {
            get {
                return ResourceManager.GetString("CLIENTS_CLIENT_TYPE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Web Application과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLIENTS_CLIENT_TYPE_WEB_APPLICATION {
            get {
                return ResourceManager.GetString("CLIENTS_CLIENT_TYPE_WEB_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please visit the address below to complete email verification.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EMAIL_VERIFY_MAIL_BODY {
            get {
                return ResourceManager.GetString("EMAIL_VERIFY_MAIL_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OAuth2 Email Verification과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EMAIL_VERIFY_MAIL_SUBJECT {
            get {
                return ResourceManager.GetString("EMAIL_VERIFY_MAIL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Some required parameters were not passed correctly.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERRORS_BAD_REQUEST {
            get {
                return ResourceManager.GetString("ERRORS_BAD_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Return to main과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERRORS_BUTTON_RETURN_TO_MAIN {
            get {
                return ResourceManager.GetString("ERRORS_BUTTON_RETURN_TO_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid access.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERRORS_INVALID_ACCESS {
            get {
                return ResourceManager.GetString("ERRORS_INVALID_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The client ID is invalid.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERRORS_INVALID_CLIENT_ID {
            get {
                return ResourceManager.GetString("ERRORS_INVALID_CLIENT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The &apos;redirect_uri&apos; is not authorized.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERRORS_INVALID_REDIRECT_URI {
            get {
                return ResourceManager.GetString("ERRORS_INVALID_REDIRECT_URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error has occurred on the page.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERRORS_TEXT_BODY {
            get {
                return ResourceManager.GetString("ERRORS_TEXT_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unsupported response type.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERRORS_UNSUPPORTED_RESPONSE_TYPE {
            get {
                return ResourceManager.GetString("ERRORS_UNSUPPORTED_RESPONSE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Continue과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_BUTTON_CONTINUE {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_BUTTON_REGISTER {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Return과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_BUTTON_RETURN {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON_RETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Continue with &apos;{0}&apos; account과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_CONTINUE_WITH_CACHED_ID {
            get {
                return ResourceManager.GetString("LOGIN_CONTINUE_WITH_CACHED_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use another account과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_CONTINUE_WITH_LOGIN {
            get {
                return ResourceManager.GetString("LOGIN_CONTINUE_WITH_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login to {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_FORM_TITLE {
            get {
                return ResourceManager.GetString("LOGIN_FORM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_LABEL_EMAIL {
            get {
                return ResourceManager.GetString("LOGIN_LABEL_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_LABEL_ID {
            get {
                return ResourceManager.GetString("LOGIN_LABEL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Full name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_LABEL_NAME {
            get {
                return ResourceManager.GetString("LOGIN_LABEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_LABEL_PW {
            get {
                return ResourceManager.GetString("LOGIN_LABEL_PW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The ID or email is already in use.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_VALIDATION_ERROR_EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("LOGIN_VALIDATION_ERROR_EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email format is invalid.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_VALIDATION_ERROR_EMAIL_INVALID_FORMAT {
            get {
                return ResourceManager.GetString("LOGIN_VALIDATION_ERROR_EMAIL_INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email is required.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_VALIDATION_ERROR_EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("LOGIN_VALIDATION_ERROR_EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID already registered.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_VALIDATION_ERROR_ID_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("LOGIN_VALIDATION_ERROR_ID_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID is not registered.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_VALIDATION_ERROR_ID_NOT_FOUND {
            get {
                return ResourceManager.GetString("LOGIN_VALIDATION_ERROR_ID_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID is required.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_VALIDATION_ERROR_ID_REQUIRED {
            get {
                return ResourceManager.GetString("LOGIN_VALIDATION_ERROR_ID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name is required.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_VALIDATION_ERROR_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("LOGIN_VALIDATION_ERROR_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The password is incorrect.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_VALIDATION_ERROR_PW_INVALID {
            get {
                return ResourceManager.GetString("LOGIN_VALIDATION_ERROR_PW_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The password is required.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_VALIDATION_ERROR_PW_REQUIRED {
            get {
                return ResourceManager.GetString("LOGIN_VALIDATION_ERROR_PW_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGE_CANCEL {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGE_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGE_CONFIRM {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGEPW_CONFIRMPW {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGEPW_CONFIRMPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGEPW_CURRENTPW {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGEPW_CURRENTPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current password is required.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGEPW_ERROR_CURRENTPWEMPTY {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGEPW_ERROR_CURRENTPWEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password confirmation does not match.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGEPW_ERROR_MISMATCHCONRIM {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGEPW_ERROR_MISMATCHCONRIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New password is required.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGEPW_ERROR_NEWPWEMPTY {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGEPW_ERROR_NEWPWEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New password must be different from the current password.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGEPW_ERROR_NOTMODIFIED {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGEPW_ERROR_NOTMODIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current password is incorrect. Please try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGEPW_ERROR_PASSWORDINCORRECT {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGEPW_ERROR_PASSWORDINCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password must be at least {0} characters long.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGEPW_ERROR_PWLENGTH {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGEPW_ERROR_PWLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password Change Failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGEPW_ERROR_TITLE {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGEPW_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGEPW_NEWPW {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGEPW_NEWPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your password has been successfully changed. You will be logged out for security.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGEPW_SUCCESS_MESSAGE {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGEPW_SUCCESS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGEPW_TITLE {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGEPW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_HEAD_PASSWORD {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_HEAD_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Identifier과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_HEAD_SUB {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_HEAD_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_PASSWORD_CHANGE {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_PASSWORD_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manage Client과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGECLIENT_TITLE {
            get {
                return ResourceManager.GetString("MANAGECLIENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manage Applications과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NAVMENU_LABEL_MANAGE_APPLICATIONS {
            get {
                return ResourceManager.GetString("NAVMENU_LABEL_MANAGE_APPLICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manage My Account과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NAVMENU_LABEL_MANAGE_MYACCOUNT {
            get {
                return ResourceManager.GetString("NAVMENU_LABEL_MANAGE_MYACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NEWCLIENT_BUTTON_PROCESSING {
            get {
                return ResourceManager.GetString("NEWCLIENT_BUTTON_PROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NEWCLIENT_BUTTON_REGISTER {
            get {
                return ResourceManager.GetString("NEWCLIENT_BUTTON_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create new client과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NEWCLIENT_BUTTONS_NEW {
            get {
                return ResourceManager.GetString("NEWCLIENT_BUTTONS_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NEWCLIENT_FORM_LABEL_NAME {
            get {
                return ResourceManager.GetString("NEWCLIENT_FORM_LABEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Client과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NEWCLIENT_TITLE {
            get {
                return ResourceManager.GetString("NEWCLIENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email verification has not been completed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NO_EMAIL_VERIFIED_MESSAGE {
            get {
                return ResourceManager.GetString("NO_EMAIL_VERIFIED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authenticate again과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NO_EMAIL_VERIFIED_REVERIFY {
            get {
                return ResourceManager.GetString("NO_EMAIL_VERIFIED_REVERIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logout과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PROFILECARD_LOGOUT {
            get {
                return ResourceManager.GetString("PROFILECARD_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   REGISTER과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string REGISTER_FORM_TITLE {
            get {
                return ResourceManager.GetString("REGISTER_FORM_TITLE", resourceCulture);
            }
        }
    }
}
