//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAuth2.Localizations {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OAuth2.Localizations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   OAuth2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string APP_TITLE {
            get {
                return ResourceManager.GetString("APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLIENTFORM_BUTTON_ADD {
            get {
                return ResourceManager.GetString("CLIENTFORM_BUTTON_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add URI과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLIENTFORM_BUTTON_ADD_URI {
            get {
                return ResourceManager.GetString("CLIENTFORM_BUTTON_ADD_URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLIENTFORM_BUTTON_APPLY {
            get {
                return ResourceManager.GetString("CLIENTFORM_BUTTON_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLIENTFORM_BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("CLIENTFORM_BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLIENTFORM_BUTTON_REMOVE {
            get {
                return ResourceManager.GetString("CLIENTFORM_BUTTON_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User not found. Please enter a valid user ID, email, or sub.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLIENTFORM_ERROR_USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("CLIENTFORM_ERROR_USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redirect URIs과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLIENTFORM_REDIRECT_URIS {
            get {
                return ResourceManager.GetString("CLIENTFORM_REDIRECT_URIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NAME과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLIENTS_CLIENT_NAME_LABEL {
            get {
                return ResourceManager.GetString("CLIENTS_CLIENT_NAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SUB과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLIENTS_CLIENT_SUB_LABEL {
            get {
                return ResourceManager.GetString("CLIENTS_CLIENT_SUB_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLIENTS_CLIENT_TYPE_LABEL {
            get {
                return ResourceManager.GetString("CLIENTS_CLIENT_TYPE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Web Application과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLIENTS_CLIENT_TYPE_WEB_APPLICATION {
            get {
                return ResourceManager.GetString("CLIENTS_CLIENT_TYPE_WEB_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please visit the address below to complete email verification.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EMAIL_VERIFY_MAIL_BODY {
            get {
                return ResourceManager.GetString("EMAIL_VERIFY_MAIL_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OAuth2 Email Verification과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EMAIL_VERIFY_MAIL_SUBJECT {
            get {
                return ResourceManager.GetString("EMAIL_VERIFY_MAIL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authentication has expired.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_COMMON_AUTHENTICATION_EXPIRED {
            get {
                return ResourceManager.GetString("ERROR_COMMON_AUTHENTICATION_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Some required parameters were not passed correctly.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERRORS_BAD_REQUEST {
            get {
                return ResourceManager.GetString("ERRORS_BAD_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Return to main과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERRORS_BUTTON_RETURN_TO_MAIN {
            get {
                return ResourceManager.GetString("ERRORS_BUTTON_RETURN_TO_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid access.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERRORS_INVALID_ACCESS {
            get {
                return ResourceManager.GetString("ERRORS_INVALID_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The client ID is invalid.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERRORS_INVALID_CLIENT_ID {
            get {
                return ResourceManager.GetString("ERRORS_INVALID_CLIENT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The &apos;redirect_uri&apos; is not authorized.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERRORS_INVALID_REDIRECT_URI {
            get {
                return ResourceManager.GetString("ERRORS_INVALID_REDIRECT_URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error has occurred on the page.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERRORS_TEXT_BODY {
            get {
                return ResourceManager.GetString("ERRORS_TEXT_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unsupported response type.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERRORS_UNSUPPORTED_RESPONSE_TYPE {
            get {
                return ResourceManager.GetString("ERRORS_UNSUPPORTED_RESPONSE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Continue과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_BUTTON_CONTINUE {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_BUTTON_REGISTER {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Return과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_BUTTON_RETURN {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON_RETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Continue with &apos;{0}&apos; account과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_CONTINUE_WITH_CACHED_ID {
            get {
                return ResourceManager.GetString("LOGIN_CONTINUE_WITH_CACHED_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use another account과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_CONTINUE_WITH_LOGIN {
            get {
                return ResourceManager.GetString("LOGIN_CONTINUE_WITH_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_CONSENT_ALLOW {
            get {
                return ResourceManager.GetString("LOGIN_CONSENT_ALLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deny과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_CONSENT_DENY {
            get {
                return ResourceManager.GetString("LOGIN_CONSENT_DENY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read your address information.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_CONSENT_SCOPE_ADDRESS {
            get {
                return ResourceManager.GetString("LOGIN_CONSENT_SCOPE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access this scope.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_CONSENT_SCOPE_DEFAULT {
            get {
                return ResourceManager.GetString("LOGIN_CONSENT_SCOPE_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read your email address.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_CONSENT_SCOPE_EMAIL {
            get {
                return ResourceManager.GetString("LOGIN_CONSENT_SCOPE_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read groups assigned to you for this application.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_CONSENT_SCOPE_GROUPS {
            get {
                return ResourceManager.GetString("LOGIN_CONSENT_SCOPE_GROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign you in and identify your account.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_CONSENT_SCOPE_OPENID {
            get {
                return ResourceManager.GetString("LOGIN_CONSENT_SCOPE_OPENID", resourceCulture);
            }
        }

        /// <summary>
        ///   Keep access when you are not actively using the application.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_CONSENT_SCOPE_OFFLINE_ACCESS {
            get {
                return ResourceManager.GetString("LOGIN_CONSENT_SCOPE_OFFLINE_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read your phone number.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_CONSENT_SCOPE_PHONE {
            get {
                return ResourceManager.GetString("LOGIN_CONSENT_SCOPE_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read your profile information.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_CONSENT_SCOPE_PROFILE {
            get {
                return ResourceManager.GetString("LOGIN_CONSENT_SCOPE_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allow {0} to access:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_CONSENT_SUMMARY {
            get {
                return ResourceManager.GetString("LOGIN_CONSENT_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login to {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_FORM_TITLE {
            get {
                return ResourceManager.GetString("LOGIN_FORM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_LABEL_EMAIL {
            get {
                return ResourceManager.GetString("LOGIN_LABEL_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_LABEL_ID {
            get {
                return ResourceManager.GetString("LOGIN_LABEL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Full name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_LABEL_NAME {
            get {
                return ResourceManager.GetString("LOGIN_LABEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_LABEL_PW {
            get {
                return ResourceManager.GetString("LOGIN_LABEL_PW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove account과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_REMOVE_CACHED_ACCOUNT {
            get {
                return ResourceManager.GetString("LOGIN_REMOVE_CACHED_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to remove the &apos;{0}&apos; account?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_REMOVE_CACHED_ACCOUNT_CONFIRM {
            get {
                return ResourceManager.GetString("LOGIN_REMOVE_CACHED_ACCOUNT_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The ID or email is already in use.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_VALIDATION_ERROR_EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("LOGIN_VALIDATION_ERROR_EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This email domain is not allowed for registration.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_VALIDATION_ERROR_EMAIL_DOMAIN_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("LOGIN_VALIDATION_ERROR_EMAIL_DOMAIN_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email format is invalid.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_VALIDATION_ERROR_EMAIL_INVALID_FORMAT {
            get {
                return ResourceManager.GetString("LOGIN_VALIDATION_ERROR_EMAIL_INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email is required.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_VALIDATION_ERROR_EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("LOGIN_VALIDATION_ERROR_EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID already registered.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_VALIDATION_ERROR_ID_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("LOGIN_VALIDATION_ERROR_ID_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID is not registered.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_VALIDATION_ERROR_ID_NOT_FOUND {
            get {
                return ResourceManager.GetString("LOGIN_VALIDATION_ERROR_ID_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID is required.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_VALIDATION_ERROR_ID_REQUIRED {
            get {
                return ResourceManager.GetString("LOGIN_VALIDATION_ERROR_ID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name is required.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_VALIDATION_ERROR_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("LOGIN_VALIDATION_ERROR_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The password is incorrect.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_VALIDATION_ERROR_PW_INVALID {
            get {
                return ResourceManager.GetString("LOGIN_VALIDATION_ERROR_PW_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Too many login attempts. Please wait a moment and try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_VALIDATION_ERROR_TOO_MANY_ATTEMPTS {
            get {
                return ResourceManager.GetString("LOGIN_VALIDATION_ERROR_TOO_MANY_ATTEMPTS", resourceCulture);
            }
        }

        /// <summary>
        ///   The password is required.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOGIN_VALIDATION_ERROR_PW_REQUIRED {
            get {
                return ResourceManager.GetString("LOGIN_VALIDATION_ERROR_PW_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_APIKEYS_CREATED_AT {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_APIKEYS_CREATED_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No API keys yet. Create a new key to enable programmatic access.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_APIKEYS_EMPTY {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_APIKEYS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key name (e.g. Production)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_APIKEYS_NAME_PLACEHOLDER {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_APIKEYS_NAME_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New API Key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_APIKEYS_NEW_BUTTON {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_APIKEYS_NEW_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove API key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_APIKEYS_REMOVE {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_APIKEYS_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to remove this API key? Any applications using it will lose access.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_APIKEYS_REMOVE_CONFIRM {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_APIKEYS_REMOVE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API Keys과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_APIKEYS_SECTION {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_APIKEYS_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manage API keys for programmatic access. Keys are stored securely and cannot be viewed after creation.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_APIKEYS_SECTION_DESC {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_APIKEYS_SECTION_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Applications과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_BACK {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete application과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_DELETE_BUTTON {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_DELETE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete this application? The application will be removed from your list.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_DELETE_CONFIRM {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_DELETE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I&apos;ve saved my API key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_NEWAPIKEY_CLOSE {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_NEWAPIKEY_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copied!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_NEWAPIKEY_COPIED {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_NEWAPIKEY_COPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_NEWAPIKEY_COPY {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_NEWAPIKEY_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API Key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_NEWAPIKEY_KEY_LABEL {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_NEWAPIKEY_KEY_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save your API key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_NEWAPIKEY_TITLE {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_NEWAPIKEY_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is the only time this key will be shown. Copy it now and store it securely — you won&apos;t be able to retrieve it again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_NEWAPIKEY_WARNING {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_NEWAPIKEY_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I&apos;ve saved my secret과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_NEWSECRET_CLOSE {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_NEWSECRET_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copied!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_NEWSECRET_COPIED {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_NEWSECRET_COPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_NEWSECRET_COPY {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_NEWSECRET_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Client Secret과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_NEWSECRET_SECRET_LABEL {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_NEWSECRET_SECRET_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save your client secret과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_NEWSECRET_TITLE {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_NEWSECRET_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is the only time this secret will be shown. Copy it now and store it securely — you won&apos;t be able to retrieve it again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_NEWSECRET_WARNING {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_NEWSECRET_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authorized redirect URIs과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_REDIRECT_SECTION {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_REDIRECT_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URIs that OAuth2 will redirect to after authorization과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_REDIRECT_SECTION_DESC {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_REDIRECT_SECTION_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_SECRETS_CREATED_AT {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_SECRETS_CREATED_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No secrets yet. Create a new secret to authenticate your application.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_SECRETS_EMPTY {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_SECRETS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Secret과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_SECRETS_NEW_BUTTON {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_SECRETS_NEW_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove secret과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_SECRETS_REMOVE {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_SECRETS_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to remove this secret? Any applications using it will lose access.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_SECRETS_REMOVE_CONFIRM {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_SECRETS_REMOVE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Client Secrets과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_SECRETS_SECTION {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_SECRETS_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manage client secrets for authentication. Secrets are stored securely and cannot be viewed after creation.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_SECRETS_SECTION_DESC {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_SECRETS_SECTION_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_SETTINGS_SECTION {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_SETTINGS_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User groups과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_USERGROUPS_SECTION {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_USERGROUPS_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Assign users to groups for this application과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATION_USERGROUPS_SECTION_DESC {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATION_USERGROUPS_SECTION_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create your first client application to get started과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATIONS_EMPTY_SUBTITLE {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATIONS_EMPTY_SUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No applications yet과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATIONS_EMPTY_TITLE {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATIONS_EMPTY_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manage your OAuth2 client applications과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGE_APPLICATIONS_SUBTITLE {
            get {
                return ResourceManager.GetString("MANAGE_APPLICATIONS_SUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All clients과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_APIKEYS_ALL_CLIENTS {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_APIKEYS_ALL_CLIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All scopes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_APIKEYS_ALL_SCOPES {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_APIKEYS_ALL_SCOPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Client과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_APIKEYS_CLIENT_LABEL {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_APIKEYS_CLIENT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allowed client ID (leave empty for all clients)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_APIKEYS_CLIENT_PLACEHOLDER {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_APIKEYS_CLIENT_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scope과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_APIKEYS_SCOPE_LABEL {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_APIKEYS_SCOPE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allowed scope (leave empty for all scopes)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_APIKEYS_SCOPE_PLACEHOLDER {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_APIKEYS_SCOPE_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manage personal API keys for programmatic access. Keys are stored securely and cannot be viewed after creation.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_APIKEYS_SECTION_DESC {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_APIKEYS_SECTION_DESC", resourceCulture);
            }
        }

        /// <summary>
        ///   No connected applications과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_GRANTS_EMPTY {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_GRANTS_EMPTY", resourceCulture);
            }
        }

        /// <summary>
        ///   Granted과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_GRANTS_GRANTED_AT {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_GRANTS_GRANTED_AT", resourceCulture);
            }
        }

        /// <summary>
        ///   Revoke access과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_GRANTS_REVOKE {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_GRANTS_REVOKE", resourceCulture);
            }
        }

        /// <summary>
        ///   Revoke access for {0}? You will need to grant permissions again next time.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_GRANTS_REVOKE_CONFIRM {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_GRANTS_REVOKE_CONFIRM", resourceCulture);
            }
        }

        /// <summary>
        ///   Scopes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_GRANTS_SCOPE_LABEL {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_GRANTS_SCOPE_LABEL", resourceCulture);
            }
        }

        /// <summary>
        ///   Review applications that can access your account and revoke access you no longer use.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_GRANTS_SECTION_DESC {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_GRANTS_SECTION_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGE_CANCEL {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGE_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGE_CONFIRM {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGEPW_CONFIRMPW {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGEPW_CONFIRMPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGEPW_CURRENTPW {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGEPW_CURRENTPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current password is required.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGEPW_ERROR_CURRENTPWEMPTY {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGEPW_ERROR_CURRENTPWEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password confirmation does not match.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGEPW_ERROR_MISMATCHCONRIM {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGEPW_ERROR_MISMATCHCONRIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New password is required.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGEPW_ERROR_NEWPWEMPTY {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGEPW_ERROR_NEWPWEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New password must be different from the current password.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGEPW_ERROR_NOTMODIFIED {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGEPW_ERROR_NOTMODIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current password is incorrect. Please try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGEPW_ERROR_PASSWORDINCORRECT {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGEPW_ERROR_PASSWORDINCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password must be at least {0} characters long.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGEPW_ERROR_PWLENGTH {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGEPW_ERROR_PWLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password Change Failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGEPW_ERROR_TITLE {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGEPW_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGEPW_NEWPW {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGEPW_NEWPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your password has been successfully changed. You will be logged out for security.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGEPW_SUCCESS_MESSAGE {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGEPW_SUCCESS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_CHANGEPW_TITLE {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_CHANGEPW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Birthdate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_HEAD_BIRTHDATE {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_HEAD_BIRTHDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_HEAD_EMAIL {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_HEAD_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Family Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_HEAD_FAMILY_NAME {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_HEAD_FAMILY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gender과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_HEAD_GENDER {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_HEAD_GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Given Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_HEAD_GIVEN_NAME {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_HEAD_GIVEN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Locale과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_HEAD_LOCALE {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_HEAD_LOCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_HEAD_NAME {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_HEAD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nickname과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_HEAD_NICKNAME {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_HEAD_NICKNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_HEAD_PASSWORD {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_HEAD_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Picture과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_HEAD_PICTURE {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_HEAD_PICTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preferred Username과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_HEAD_PREFERRED_USERNAME {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_HEAD_PREFERRED_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Identifier과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_HEAD_SUB {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_HEAD_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last Updated과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_HEAD_UPDATEDAT {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_HEAD_UPDATEDAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Website과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_HEAD_WEBSITE {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_HEAD_WEBSITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time Zone과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_HEAD_ZONEINFO {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_HEAD_ZONEINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My Account과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_PAGE_TITLE {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_PASSWORD_CHANGE {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_PASSWORD_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_PROFILE_EDIT {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_PROFILE_EDIT", resourceCulture);
            }
        }

        /// <summary>
        ///   Website must be a valid http or https URL.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_PROFILE_EDIT_INVALID_WEBSITE {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_PROFILE_EDIT_INVALID_WEBSITE", resourceCulture);
            }
        }

        /// <summary>
        ///   Display name is required.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_PROFILE_EDIT_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_PROFILE_EDIT_NAME_REQUIRED", resourceCulture);
            }
        }

        /// <summary>
        ///   No changes.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_PROFILE_EDIT_NOCHANGE {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_PROFILE_EDIT_NOCHANGE", resourceCulture);
            }
        }

        /// <summary>
        ///   Your profile has been successfully changed. You will be logged out for refresh.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_PROFILE_EDIT_SUCCESS_MESSAGE {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_PROFILE_EDIT_SUCCESS_MESSAGE", resourceCulture);
            }
        }

        /// <summary>
        ///   Edit Profile과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_PROFILE_EDIT_TITLE {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_PROFILE_EDIT_TITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Change과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_PICTURE_CHANGE {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_PICTURE_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No changes.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_PICTURE_CHANGE_NOCHANGE {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_PICTURE_CHANGE_NOCHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your picture has been successfully changed. You will be logged out for refresh.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_PICTURE_CHANGE_SUCCESS_MESSAGE {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_PICTURE_CHANGE_SUCCESS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Picture과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_PICTURE_CHANGE_TITLE {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_PICTURE_CHANGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Picture URI must be a valid http or https URL.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_PICTURE_ERROR_INVALID_URL {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_PICTURE_ERROR_INVALID_URL", resourceCulture);
            }
        }

        /// <summary>
        ///   Picture must be at most {0}x{1} pixels.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_PICTURE_ERROR_INVALID_DIMENSIONS {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_PICTURE_ERROR_INVALID_DIMENSIONS", resourceCulture);
            }
        }

        /// <summary>
        ///   Select a picture to upload.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_PICTURE_ERROR_REQUIRED {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_PICTURE_ERROR_REQUIRED", resourceCulture);
            }
        }

        /// <summary>
        ///   Picture must be {0} KB or smaller.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_PICTURE_ERROR_TOO_LARGE {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_PICTURE_ERROR_TOO_LARGE", resourceCulture);
            }
        }

        /// <summary>
        ///   Picture upload failed. Please try another image.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_PICTURE_ERROR_UPLOAD_FAILED {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_PICTURE_ERROR_UPLOAD_FAILED", resourceCulture);
            }
        }

        /// <summary>
        ///   Use a PNG or JPEG image.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_PICTURE_ERROR_UNSUPPORTED_FORMAT {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_PICTURE_ERROR_UNSUPPORTED_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Picture Uri과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_PICTURE_URI {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_PICTURE_URI", resourceCulture);
            }
        }

        /// <summary>
        ///   Select image과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_PICTURE_UPLOAD_SELECT {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_PICTURE_UPLOAD_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Account과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_SECTION_ACCOUNT {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_SECTION_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API Keys과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_SECTION_APIKEYS {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_SECTION_APIKEYS", resourceCulture);
            }
        }

        /// <summary>
        ///   Connected Applications과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_SECTION_GRANTS {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_SECTION_GRANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_SECTION_PROFILE {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_SECTION_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Security과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_SECTION_SECURITY {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_SECTION_SECURITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Verified과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_VALUE_EMAIL_NOT_VERIFIED {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_VALUE_EMAIL_NOT_VERIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verified과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGEACCOUNTS_VALUE_EMAIL_VERIFIED {
            get {
                return ResourceManager.GetString("MANAGEACCOUNTS_VALUE_EMAIL_VERIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manage Client과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MANAGECLIENT_TITLE {
            get {
                return ResourceManager.GetString("MANAGECLIENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manage Applications과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NAVMENU_LABEL_MANAGE_APPLICATIONS {
            get {
                return ResourceManager.GetString("NAVMENU_LABEL_MANAGE_APPLICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manage My Account과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NAVMENU_LABEL_MANAGE_MYACCOUNT {
            get {
                return ResourceManager.GetString("NAVMENU_LABEL_MANAGE_MYACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NEWCLIENT_BUTTON_PROCESSING {
            get {
                return ResourceManager.GetString("NEWCLIENT_BUTTON_PROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NEWCLIENT_BUTTON_REGISTER {
            get {
                return ResourceManager.GetString("NEWCLIENT_BUTTON_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create new client과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NEWCLIENT_BUTTONS_NEW {
            get {
                return ResourceManager.GetString("NEWCLIENT_BUTTONS_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NEWCLIENT_FORM_LABEL_NAME {
            get {
                return ResourceManager.GetString("NEWCLIENT_FORM_LABEL_NAME", resourceCulture);
            }
        }

        /// <summary>
        ///   Application ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NEWCLIENT_FORM_LABEL_CLIENT_ID {
            get {
                return ResourceManager.GetString("NEWCLIENT_FORM_LABEL_CLIENT_ID", resourceCulture);
            }
        }

        /// <summary>
        ///   Use letters, numbers, '.', '_' or '-'.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NEWCLIENT_FORM_HELP_CLIENT_ID {
            get {
                return ResourceManager.GetString("NEWCLIENT_FORM_HELP_CLIENT_ID", resourceCulture);
            }
        }

        /// <summary>
        ///   Application ID is required.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NEWCLIENT_VALIDATION_ERROR_CLIENT_ID_REQUIRED {
            get {
                return ResourceManager.GetString("NEWCLIENT_VALIDATION_ERROR_CLIENT_ID_REQUIRED", resourceCulture);
            }
        }

        /// <summary>
        ///   Application ID can only contain letters, numbers, '.', '_' and '-'.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NEWCLIENT_VALIDATION_ERROR_CLIENT_ID_INVALID {
            get {
                return ResourceManager.GetString("NEWCLIENT_VALIDATION_ERROR_CLIENT_ID_INVALID", resourceCulture);
            }
        }

        /// <summary>
        ///   Application ID must be {0} characters or fewer.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NEWCLIENT_VALIDATION_ERROR_CLIENT_ID_TOO_LONG {
            get {
                return ResourceManager.GetString("NEWCLIENT_VALIDATION_ERROR_CLIENT_ID_TOO_LONG", resourceCulture);
            }
        }

        /// <summary>
        ///   Application ID is already in use.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NEWCLIENT_VALIDATION_ERROR_CLIENT_ID_DUPLICATE {
            get {
                return ResourceManager.GetString("NEWCLIENT_VALIDATION_ERROR_CLIENT_ID_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Client과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NEWCLIENT_TITLE {
            get {
                return ResourceManager.GetString("NEWCLIENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email verification has not been completed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NO_EMAIL_VERIFIED_MESSAGE {
            get {
                return ResourceManager.GetString("NO_EMAIL_VERIFIED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authenticate again과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NO_EMAIL_VERIFIED_REVERIFY {
            get {
                return ResourceManager.GetString("NO_EMAIL_VERIFIED_REVERIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logout과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PROFILECARD_LOGOUT {
            get {
                return ResourceManager.GetString("PROFILECARD_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   REGISTER과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string REGISTER_FORM_TITLE {
            get {
                return ResourceManager.GetString("REGISTER_FORM_TITLE", resourceCulture);
            }
        }
    }
}
