<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Master</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gateway.Abstractions\Gateway.Abstractions.csproj" />
    <ProjectReference Include="..\Master.Abstractions\Master.Abstractions.csproj" />
    <ProjectReference Include="..\Scripting.Abstractions\Scripting.Abstractions.csproj" />
  </ItemGroup>

</Project>
