namespace JenkinsFailureAnalyzer.Services;

public sealed class RuleBasedFailureAnalysisService : IFailureAnalysisService
{
    private static readonly string[] s_ErrorKeywords = ["error", "exception", "failed", "failure", "timeout", "denied"];

    public ValueTask<FailureAnalysisResult> AnalyzeAsync(FailureAnalysisSubmission submission, CancellationToken cancellationToken)
    {
        var evidenceLines = submission.Content
            .Split('\n')
            .Select(static line => line.Trim())
            .Where(static line => !string.IsNullOrWhiteSpace(line))
            .Where(static line => s_ErrorKeywords.Any(keyword => line.Contains(keyword, StringComparison.OrdinalIgnoreCase)))
            .Take(5)
            .ToArray();

        var likelyCauses = evidenceLines.Length == 0
            ? ["No obvious failure marker was found in the submitted content."]
            : evidenceLines.Select(static line => $"Log evidence: {line}").ToArray();

        var suggestedActions = new[]
        {
            "Review the captured log evidence and compare it with the Jenkins stage that failed.",
            "Attach the full build log or failing artifact when escalating the issue.",
            "Replace the placeholder analyzer with the configured AI provider once model settings are available."
        };

        var jobName = submission.JobName ?? "Jenkins job";
        var buildNumber = submission.BuildNumber is null ? string.Empty : $" build {submission.BuildNumber}";
        var summary = $"{jobName}{buildNumber} failed. AI provider integration is not configured yet, so this response is generated by the bootstrap rule-based analyzer.";
        return ValueTask.FromResult(new FailureAnalysisResult(summary, likelyCauses, suggestedActions));
    }
}
