<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.SimpleEmail" Version="4.0.2.17" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.8" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.StackExchangeRedis" Version="10.0.5" />
    <PackageReference Include="MySql.Data" Version="9.4.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ASPNETUtility\ASPNETUtility.csproj" />
    <ProjectReference Include="..\BlazorSharedComponent\BlazorSharedComponent.csproj" />
    <ProjectReference Include="..\OAuth2.Controllers\OAuth2.Controllers.csproj" />
    <ProjectReference Include="..\OAuth2.SQL\OAuth2.SQL.csproj" />
    <ProjectReference Include="..\OAuth2.Core\OAuth2.Core.csproj" />
    <ProjectReference Include="..\SQLMigration\SQLMigration.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Localizations\Strings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Localizations\Strings.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
