<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Scripting.DTO\Scripting.DTO.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Components\AppStrings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AppStrings.resx</DependentUpon>
    </Compile>
    <Compile Update="Components\Pages\Auth\LoginStrings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LoginStrings.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Components\AppStrings.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AppStrings.Designer.cs</LastGenOutput>
      <DependentUpon>App.razor</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Components\AppStrings.ko.resx">
      <DependentUpon>AppStrings.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Components\Pages\Auth\LoginStrings.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>LoginStrings.Designer.cs</LastGenOutput>
      <DependentUpon>Login.razor</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Components\Pages\Auth\LoginStrings.ko.resx">
      <DependentUpon>LoginStrings.resx</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

</Project>
