//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterAdmin.Localizations {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MasterAdmin.Localizations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   MasterServer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string APP_TITLE {
            get {
                return ResourceManager.GetString("APP_TITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   This management page requires the admin role.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ACCESS_DENIED_DESCRIPTION {
            get {
                return ResourceManager.GetString("ACCESS_DENIED_DESCRIPTION", resourceCulture);
            }
        }

        /// <summary>
        ///   Access denied과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ACCESS_DENIED_TITLE {
            get {
                return ResourceManager.GetString("ACCESS_DENIED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} active과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CONNECTIONS_ACTIVE_FORMAT {
            get {
                return ResourceManager.GetString("CONNECTIONS_ACTIVE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current socket peers observed by the Master hosted service.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CONNECTIONS_DESCRIPTION {
            get {
                return ResourceManager.GetString("CONNECTIONS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gateway and Dedicated registration can be added on top of this socket surface.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CONNECTIONS_EMPTY_DESCRIPTION {
            get {
                return ResourceManager.GetString("CONNECTIONS_EMPTY_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No node connections과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CONNECTIONS_EMPTY_TITLE {
            get {
                return ResourceManager.GetString("CONNECTIONS_EMPTY_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CONNECTIONS_TABLE_CONNECTED {
            get {
                return ResourceManager.GetString("CONNECTIONS_TABLE_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CONNECTIONS_TABLE_CONNECTION {
            get {
                return ResourceManager.GetString("CONNECTIONS_TABLE_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last seen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CONNECTIONS_TABLE_LAST_SEEN {
            get {
                return ResourceManager.GetString("CONNECTIONS_TABLE_LAST_SEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remote endpoint과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CONNECTIONS_TABLE_REMOTE_ENDPOINT {
            get {
                return ResourceManager.GetString("CONNECTIONS_TABLE_REMOTE_ENDPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Role과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CONNECTIONS_TABLE_ROLE {
            get {
                return ResourceManager.GetString("CONNECTIONS_TABLE_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Node Connections과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CONNECTIONS_TITLE {
            get {
                return ResourceManager.GetString("CONNECTIONS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Swapping to Development environment will display more detailed information about the error that occurred.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_DEVELOPMENT_MODE_DESCRIPTION {
            get {
                return ResourceManager.GetString("ERROR_DEVELOPMENT_MODE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Development Mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_DEVELOPMENT_MODE_TITLE {
            get {
                return ResourceManager.GetString("ERROR_DEVELOPMENT_MODE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Development environment should not be enabled for deployed applications.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_DEVELOPMENT_MODE_WARNING {
            get {
                return ResourceManager.GetString("ERROR_DEVELOPMENT_MODE_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while processing your request.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_PAGE_MESSAGE {
            get {
                return ResourceManager.GetString("ERROR_PAGE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_PAGE_TITLE {
            get {
                return ResourceManager.GetString("ERROR_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Request ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_REQUEST_ID {
            get {
                return ResourceManager.GetString("ERROR_REQUEST_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MasterServer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HOME_EYEBROW {
            get {
                return ResourceManager.GetString("HOME_EYEBROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gateway and Dedicated nodes connect here for control-plane state. Packet relay and game data stay outside Master.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HOME_SUMMARY {
            get {
                return ResourceManager.GetString("HOME_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Master summary과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HOME_SUMMARY_ARIA {
            get {
                return ResourceManager.GetString("HOME_SUMMARY_ARIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Control Plane과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HOME_TITLE {
            get {
                return ResourceManager.GetString("HOME_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Active connections과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string METRIC_ACTIVE_CONNECTIONS {
            get {
                return ResourceManager.GetString("METRIC_ACTIVE_CONNECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gateway/Dedicated role handshake pending과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string METRIC_ACTIVE_CONNECTIONS_DETAIL {
            get {
                return ResourceManager.GetString("METRIC_ACTIVE_CONNECTIONS_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Control mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string METRIC_CONTROL_MODE {
            get {
                return ResourceManager.GetString("METRIC_CONTROL_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready for lease and ownership extensions과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string METRIC_CONTROL_MODE_DETAIL {
            get {
                return ResourceManager.GetString("METRIC_CONTROL_MODE_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single Master과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string METRIC_CONTROL_MODE_VALUE {
            get {
                return ResourceManager.GetString("METRIC_CONTROL_MODE_VALUE", resourceCulture);
            }
        }

        /// <summary>
        ///   Master socket과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string METRIC_MASTER_SOCKET {
            get {
                return ResourceManager.GetString("METRIC_MASTER_SOCKET", resourceCulture);
            }
        }

        /// <summary>
        ///   Receiving live snapshots over the shared packet socket과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MASTER_SOCKET_CONNECTED_DETAIL {
            get {
                return ResourceManager.GetString("MASTER_SOCKET_CONNECTED_DETAIL", resourceCulture);
            }
        }

        /// <summary>
        ///   Last socket event: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MASTER_SOCKET_LAST_ERROR_FORMAT {
            get {
                return ResourceManager.GetString("MASTER_SOCKET_LAST_ERROR_FORMAT", resourceCulture);
            }
        }

        /// <summary>
        ///   Next reconnect at {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MASTER_SOCKET_RECONNECTING_DETAIL_FORMAT {
            get {
                return ResourceManager.GetString("MASTER_SOCKET_RECONNECTING_DETAIL_FORMAT", resourceCulture);
            }
        }

        /// <summary>
        ///   Connected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MASTER_SOCKET_STATUS_CONNECTED {
            get {
                return ResourceManager.GetString("MASTER_SOCKET_STATUS_CONNECTED", resourceCulture);
            }
        }

        /// <summary>
        ///   Connecting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MASTER_SOCKET_STATUS_CONNECTING {
            get {
                return ResourceManager.GetString("MASTER_SOCKET_STATUS_CONNECTING", resourceCulture);
            }
        }

        /// <summary>
        ///   Disabled과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MASTER_SOCKET_STATUS_DISABLED {
            get {
                return ResourceManager.GetString("MASTER_SOCKET_STATUS_DISABLED", resourceCulture);
            }
        }

        /// <summary>
        ///   Disconnected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MASTER_SOCKET_STATUS_DISCONNECTED {
            get {
                return ResourceManager.GetString("MASTER_SOCKET_STATUS_DISCONNECTED", resourceCulture);
            }
        }

        /// <summary>
        ///   Handshaking과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MASTER_SOCKET_STATUS_HANDSHAKING {
            get {
                return ResourceManager.GetString("MASTER_SOCKET_STATUS_HANDSHAKING", resourceCulture);
            }
        }

        /// <summary>
        ///   Reconnecting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MASTER_SOCKET_STATUS_RECONNECTING {
            get {
                return ResourceManager.GetString("MASTER_SOCKET_STATUS_RECONNECTING", resourceCulture);
            }
        }

        /// <summary>
        ///   Stopping과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MASTER_SOCKET_STATUS_STOPPING {
            get {
                return ResourceManager.GetString("MASTER_SOCKET_STATUS_STOPPING", resourceCulture);
            }
        }

        /// <summary>
        ///   Waiting for Master socket state과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MASTER_SOCKET_WAITING_DETAIL {
            get {
                return ResourceManager.GetString("MASTER_SOCKET_WAITING_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Socket endpoint과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string METRIC_SOCKET_ENDPOINT {
            get {
                return ResourceManager.GetString("METRIC_SOCKET_ENDPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overview과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NAV_OVERVIEW {
            get {
                return ResourceManager.GetString("NAV_OVERVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Navigation menu과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NAV_TOGGLE_TITLE {
            get {
                return ResourceManager.GetString("NAV_TOGGLE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dedicated과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_KIND_DEDICATED {
            get {
                return ResourceManager.GetString("NODE_KIND_DEDICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gateway과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_KIND_GATEWAY {
            get {
                return ResourceManager.GetString("NODE_KIND_GATEWAY", resourceCulture);
            }
        }

        /// <summary>
        ///   Master Admin과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_KIND_MASTER_ADMIN {
            get {
                return ResourceManager.GetString("NODE_KIND_MASTER_ADMIN", resourceCulture);
            }
        }

        /// <summary>
        ///   Back to overview과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_BACK_TO_OVERVIEW {
            get {
                return ResourceManager.GetString("NODE_BACK_TO_OVERVIEW", resourceCulture);
            }
        }

        /// <summary>
        ///   Master Relay과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_PAGE_EYEBROW {
            get {
                return ResourceManager.GetString("NODE_PAGE_EYEBROW", resourceCulture);
            }
        }

        /// <summary>
        ///   Service status is requested through the Master control-plane socket, not by connecting to the service directly.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_PAGE_SUMMARY {
            get {
                return ResourceManager.GetString("NODE_PAGE_SUMMARY", resourceCulture);
            }
        }

        /// <summary>
        ///   Node Management과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_PAGE_TITLE {
            get {
                return ResourceManager.GetString("NODE_PAGE_TITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Refresh과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_REFRESH {
            get {
                return ResourceManager.GetString("NODE_REFRESH", resourceCulture);
            }
        }

        /// <summary>
        ///   Refreshing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_REFRESHING {
            get {
                return ResourceManager.GetString("NODE_REFRESHING", resourceCulture);
            }
        }

        /// <summary>
        ///   Connected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_STATUS_CONNECTED {
            get {
                return ResourceManager.GetString("NODE_STATUS_CONNECTED", resourceCulture);
            }
        }

        /// <summary>
        ///   Current management data returned by the selected service through Master.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_STATUS_DESCRIPTION {
            get {
                return ResourceManager.GetString("NODE_STATUS_DESCRIPTION", resourceCulture);
            }
        }

        /// <summary>
        ///   No status items과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_STATUS_EMPTY_TITLE {
            get {
                return ResourceManager.GetString("NODE_STATUS_EMPTY_TITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   The service is connected but has not exposed additional management data yet.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_STATUS_EMPTY_DESCRIPTION {
            get {
                return ResourceManager.GetString("NODE_STATUS_EMPTY_DESCRIPTION", resourceCulture);
            }
        }

        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_STATUS_ERROR {
            get {
                return ResourceManager.GetString("NODE_STATUS_ERROR", resourceCulture);
            }
        }

        /// <summary>
        ///   Status unavailable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_STATUS_ERROR_TITLE {
            get {
                return ResourceManager.GetString("NODE_STATUS_ERROR_TITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Connection id is invalid.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_STATUS_INVALID_CONNECTION {
            get {
                return ResourceManager.GetString("NODE_STATUS_INVALID_CONNECTION", resourceCulture);
            }
        }

        /// <summary>
        ///   Loading과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_STATUS_LOADING {
            get {
                return ResourceManager.GetString("NODE_STATUS_LOADING", resourceCulture);
            }
        }

        /// <summary>
        ///   Waiting for the selected service to answer through Master.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_STATUS_LOADING_DESCRIPTION {
            get {
                return ResourceManager.GetString("NODE_STATUS_LOADING_DESCRIPTION", resourceCulture);
            }
        }

        /// <summary>
        ///   Loading status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_STATUS_LOADING_TITLE {
            get {
                return ResourceManager.GetString("NODE_STATUS_LOADING_TITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Relay status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_STATUS_RELAY {
            get {
                return ResourceManager.GetString("NODE_STATUS_RELAY", resourceCulture);
            }
        }

        /// <summary>
        ///   Related nodes that can be opened through the Master relay path.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_RELATED_DESCRIPTION {
            get {
                return ResourceManager.GetString("NODE_RELATED_DESCRIPTION", resourceCulture);
            }
        }

        /// <summary>
        ///   This service has no related Gateway or Dedicated connection to show.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_RELATED_EMPTY_DESCRIPTION {
            get {
                return ResourceManager.GetString("NODE_RELATED_EMPTY_DESCRIPTION", resourceCulture);
            }
        }

        /// <summary>
        ///   No connected services과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_RELATED_EMPTY_TITLE {
            get {
                return ResourceManager.GetString("NODE_RELATED_EMPTY_TITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Connected Services과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_RELATED_TITLE {
            get {
                return ResourceManager.GetString("NODE_RELATED_TITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   The service did not answer before the request timed out.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_STATUS_TIMEOUT {
            get {
                return ResourceManager.GetString("NODE_STATUS_TIMEOUT", resourceCulture);
            }
        }

        /// <summary>
        ///   Service Status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_STATUS_TITLE {
            get {
                return ResourceManager.GetString("NODE_STATUS_TITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Unavailable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_STATUS_UNAVAILABLE {
            get {
                return ResourceManager.GetString("NODE_STATUS_UNAVAILABLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Node summary과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_SUMMARY_ARIA {
            get {
                return ResourceManager.GetString("NODE_SUMMARY_ARIA", resourceCulture);
            }
        }

        /// <summary>
        ///   Unknown connection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_UNKNOWN_CONNECTION {
            get {
                return ResourceManager.GetString("NODE_UNKNOWN_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NODE_KIND_UNKNOWN {
            get {
                return ResourceManager.GetString("NODE_KIND_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The requested MasterServer page does not exist.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NOTFOUND_DESCRIPTION {
            get {
                return ResourceManager.GetString("NOTFOUND_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Found과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NOTFOUND_TITLE {
            get {
                return ResourceManager.GetString("NOTFOUND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TLS disabled과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TLS_DISABLED {
            get {
                return ResourceManager.GetString("TLS_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TLS enabled과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TLS_ENABLED {
            get {
                return ResourceManager.GetString("TLS_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backend과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TOPBAR_SECTION_BACKEND {
            get {
                return ResourceManager.GetString("TOPBAR_SECTION_BACKEND", resourceCulture);
            }
        }
    }
}
