//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace GatewayServer.Localizations
{
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings
    {
        private static global::System.Resources.ResourceManager? resourceMan;
        private static global::System.Globalization.CultureInfo? resourceCulture;

        internal Strings()
        {
        }

        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GatewayServer.Localizations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        internal static global::System.Globalization.CultureInfo? Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        private static string GetString(string name)
        {
            return ResourceManager.GetString(name, resourceCulture) ?? string.Empty;
        }

        internal static string ACCESS_DENIED_DESCRIPTION => GetString("ACCESS_DENIED_DESCRIPTION");
        internal static string ACCESS_DENIED_TITLE => GetString("ACCESS_DENIED_TITLE");
        internal static string APP_TITLE => GetString("APP_TITLE");
        internal static string DIAGNOSTICS_DESCRIPTION => GetString("DIAGNOSTICS_DESCRIPTION");
        internal static string DIAGNOSTICS_PAGE_TITLE => GetString("DIAGNOSTICS_PAGE_TITLE");
        internal static string DIAGNOSTICS_TABLE_DATE => GetString("DIAGNOSTICS_TABLE_DATE");
        internal static string DIAGNOSTICS_TABLE_SUMMARY => GetString("DIAGNOSTICS_TABLE_SUMMARY");
        internal static string DIAGNOSTICS_TABLE_TEMP_C => GetString("DIAGNOSTICS_TABLE_TEMP_C");
        internal static string DIAGNOSTICS_TABLE_TEMP_C_ARIA => GetString("DIAGNOSTICS_TABLE_TEMP_C_ARIA");
        internal static string DIAGNOSTICS_TABLE_TEMP_F => GetString("DIAGNOSTICS_TABLE_TEMP_F");
        internal static string DIAGNOSTICS_TABLE_TEMP_F_ARIA => GetString("DIAGNOSTICS_TABLE_TEMP_F_ARIA");
        internal static string DIAGNOSTICS_TITLE => GetString("DIAGNOSTICS_TITLE");
        internal static string ERROR_DEVELOPMENT_MODE_DESCRIPTION => GetString("ERROR_DEVELOPMENT_MODE_DESCRIPTION");
        internal static string ERROR_DEVELOPMENT_MODE_TITLE => GetString("ERROR_DEVELOPMENT_MODE_TITLE");
        internal static string ERROR_DEVELOPMENT_MODE_WARNING => GetString("ERROR_DEVELOPMENT_MODE_WARNING");
        internal static string ERROR_PAGE_MESSAGE => GetString("ERROR_PAGE_MESSAGE");
        internal static string ERROR_PAGE_TITLE => GetString("ERROR_PAGE_TITLE");
        internal static string ERROR_REQUEST_ID => GetString("ERROR_REQUEST_ID");
        internal static string HOME_EYEBROW => GetString("HOME_EYEBROW");
        internal static string HOME_SUMMARY => GetString("HOME_SUMMARY");
        internal static string HOME_SUMMARY_ARIA => GetString("HOME_SUMMARY_ARIA");
        internal static string HOME_TITLE => GetString("HOME_TITLE");
        internal static string LOADING => GetString("LOADING");
        internal static string METRIC_CLIENT_EDGE => GetString("METRIC_CLIENT_EDGE");
        internal static string METRIC_CLIENT_EDGE_DETAIL => GetString("METRIC_CLIENT_EDGE_DETAIL");
        internal static string METRIC_CLIENT_EDGE_VALUE => GetString("METRIC_CLIENT_EDGE_VALUE");
        internal static string METRIC_CONTROL_PLANE => GetString("METRIC_CONTROL_PLANE");
        internal static string METRIC_CONTROL_PLANE_DETAIL => GetString("METRIC_CONTROL_PLANE_DETAIL");
        internal static string METRIC_CONTROL_PLANE_VALUE => GetString("METRIC_CONTROL_PLANE_VALUE");
        internal static string METRIC_ROUTING_MODE => GetString("METRIC_ROUTING_MODE");
        internal static string METRIC_ROUTING_MODE_DETAIL => GetString("METRIC_ROUTING_MODE_DETAIL");
        internal static string METRIC_ROUTING_MODE_VALUE => GetString("METRIC_ROUTING_MODE_VALUE");
        internal static string NAV_DIAGNOSTICS => GetString("NAV_DIAGNOSTICS");
        internal static string NAV_OVERVIEW => GetString("NAV_OVERVIEW");
        internal static string NAV_TOGGLE_TITLE => GetString("NAV_TOGGLE_TITLE");
        internal static string NOTFOUND_DESCRIPTION => GetString("NOTFOUND_DESCRIPTION");
        internal static string NOTFOUND_TITLE => GetString("NOTFOUND_TITLE");
        internal static string OPERATIONS_CLIENT_AREA => GetString("OPERATIONS_CLIENT_AREA");
        internal static string OPERATIONS_CLIENT_NOTES => GetString("OPERATIONS_CLIENT_NOTES");
        internal static string OPERATIONS_DEDICATED_AREA => GetString("OPERATIONS_DEDICATED_AREA");
        internal static string OPERATIONS_DEDICATED_NOTES => GetString("OPERATIONS_DEDICATED_NOTES");
        internal static string OPERATIONS_DESCRIPTION => GetString("OPERATIONS_DESCRIPTION");
        internal static string OPERATIONS_MASTER_AREA => GetString("OPERATIONS_MASTER_AREA");
        internal static string OPERATIONS_MASTER_NOTES => GetString("OPERATIONS_MASTER_NOTES");
        internal static string OPERATIONS_STATE_ACTIVE => GetString("OPERATIONS_STATE_ACTIVE");
        internal static string OPERATIONS_STATE_CONFIGURED => GetString("OPERATIONS_STATE_CONFIGURED");
        internal static string OPERATIONS_STATE_PENDING => GetString("OPERATIONS_STATE_PENDING");
        internal static string OPERATIONS_STATUS => GetString("OPERATIONS_STATUS");
        internal static string OPERATIONS_TABLE_AREA => GetString("OPERATIONS_TABLE_AREA");
        internal static string OPERATIONS_TABLE_NOTES => GetString("OPERATIONS_TABLE_NOTES");
        internal static string OPERATIONS_TABLE_STATE => GetString("OPERATIONS_TABLE_STATE");
        internal static string OPERATIONS_TITLE => GetString("OPERATIONS_TITLE");
        internal static string TOPBAR_SECTION_BACKEND => GetString("TOPBAR_SECTION_BACKEND");
        internal static string WEATHER_BALMY => GetString("WEATHER_BALMY");
        internal static string WEATHER_BRACING => GetString("WEATHER_BRACING");
        internal static string WEATHER_CHILLY => GetString("WEATHER_CHILLY");
        internal static string WEATHER_COOL => GetString("WEATHER_COOL");
        internal static string WEATHER_FREEZING => GetString("WEATHER_FREEZING");
        internal static string WEATHER_HOT => GetString("WEATHER_HOT");
        internal static string WEATHER_MILD => GetString("WEATHER_MILD");
        internal static string WEATHER_SCORCHING => GetString("WEATHER_SCORCHING");
        internal static string WEATHER_SWELTERING => GetString("WEATHER_SWELTERING");
        internal static string WEATHER_WARM => GetString("WEATHER_WARM");
    }
}
