//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GatewayServer.Localizations {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GatewayServer.Localizations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   This management page requires the admin role.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ACCESS_DENIED_DESCRIPTION {
            get {
                return ResourceManager.GetString("ACCESS_DENIED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access denied과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ACCESS_DENIED_TITLE {
            get {
                return ResourceManager.GetString("ACCESS_DENIED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GatewayServer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string APP_TITLE {
            get {
                return ResourceManager.GetString("APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This page keeps the template streaming example available for local rendering checks.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIAGNOSTICS_DESCRIPTION {
            get {
                return ResourceManager.GetString("DIAGNOSTICS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagnostics과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIAGNOSTICS_PAGE_TITLE {
            get {
                return ResourceManager.GetString("DIAGNOSTICS_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIAGNOSTICS_TABLE_DATE {
            get {
                return ResourceManager.GetString("DIAGNOSTICS_TABLE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Summary과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIAGNOSTICS_TABLE_SUMMARY {
            get {
                return ResourceManager.GetString("DIAGNOSTICS_TABLE_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temp. (C)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIAGNOSTICS_TABLE_TEMP_C {
            get {
                return ResourceManager.GetString("DIAGNOSTICS_TABLE_TEMP_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temperature in Celsius과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIAGNOSTICS_TABLE_TEMP_C_ARIA {
            get {
                return ResourceManager.GetString("DIAGNOSTICS_TABLE_TEMP_C_ARIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temp. (F)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIAGNOSTICS_TABLE_TEMP_F {
            get {
                return ResourceManager.GetString("DIAGNOSTICS_TABLE_TEMP_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temperature in Fahrenheit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIAGNOSTICS_TABLE_TEMP_F_ARIA {
            get {
                return ResourceManager.GetString("DIAGNOSTICS_TABLE_TEMP_F_ARIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagnostics과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIAGNOSTICS_TITLE {
            get {
                return ResourceManager.GetString("DIAGNOSTICS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Swapping to Development environment will display more detailed information about the error that occurred.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_DEVELOPMENT_MODE_DESCRIPTION {
            get {
                return ResourceManager.GetString("ERROR_DEVELOPMENT_MODE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Development Mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_DEVELOPMENT_MODE_TITLE {
            get {
                return ResourceManager.GetString("ERROR_DEVELOPMENT_MODE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Development environment should not be enabled for deployed applications.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_DEVELOPMENT_MODE_WARNING {
            get {
                return ResourceManager.GetString("ERROR_DEVELOPMENT_MODE_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while processing your request.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_PAGE_MESSAGE {
            get {
                return ResourceManager.GetString("ERROR_PAGE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_PAGE_TITLE {
            get {
                return ResourceManager.GetString("ERROR_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Request ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_REQUEST_ID {
            get {
                return ResourceManager.GetString("ERROR_REQUEST_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GatewayServer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HOME_EYEBROW {
            get {
                return ResourceManager.GetString("HOME_EYEBROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gateway accepts client sessions, validates PacketCore traffic, and routes trusted play traffic toward Dedicated servers while staying outside authoritative game logic.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HOME_SUMMARY {
            get {
                return ResourceManager.GetString("HOME_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gateway summary과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HOME_SUMMARY_ARIA {
            get {
                return ResourceManager.GetString("HOME_SUMMARY_ARIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Client Edge과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HOME_TITLE {
            get {
                return ResourceManager.GetString("HOME_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOADING {
            get {
                return ResourceManager.GetString("LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Client edge과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string METRIC_CLIENT_EDGE {
            get {
                return ResourceManager.GetString("METRIC_CLIENT_EDGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Common frame validation for incoming packets과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string METRIC_CLIENT_EDGE_DETAIL {
            get {
                return ResourceManager.GetString("METRIC_CLIENT_EDGE_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PacketCore과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string METRIC_CLIENT_EDGE_VALUE {
            get {
                return ResourceManager.GetString("METRIC_CLIENT_EDGE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Control plane과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string METRIC_CONTROL_PLANE {
            get {
                return ResourceManager.GetString("METRIC_CONTROL_PLANE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application-level node proof before trust과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string METRIC_CONTROL_PLANE_DETAIL {
            get {
                return ResourceManager.GetString("METRIC_CONTROL_PLANE_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Master handshake과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string METRIC_CONTROL_PLANE_VALUE {
            get {
                return ResourceManager.GetString("METRIC_CONTROL_PLANE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Routing mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string METRIC_ROUTING_MODE {
            get {
                return ResourceManager.GetString("METRIC_ROUTING_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prepared for channel ownership from Master과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string METRIC_ROUTING_MODE_DETAIL {
            get {
                return ResourceManager.GetString("METRIC_ROUTING_MODE_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dedicated relay과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string METRIC_ROUTING_MODE_VALUE {
            get {
                return ResourceManager.GetString("METRIC_ROUTING_MODE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagnostics과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NAV_DIAGNOSTICS {
            get {
                return ResourceManager.GetString("NAV_DIAGNOSTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overview과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NAV_OVERVIEW {
            get {
                return ResourceManager.GetString("NAV_OVERVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Navigation menu과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NAV_TOGGLE_TITLE {
            get {
                return ResourceManager.GetString("NAV_TOGGLE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The requested GatewayServer page does not exist.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NOTFOUND_DESCRIPTION {
            get {
                return ResourceManager.GetString("NOTFOUND_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Found과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NOTFOUND_TITLE {
            get {
                return ResourceManager.GetString("NOTFOUND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Client sockets과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OPERATIONS_CLIENT_AREA {
            get {
                return ResourceManager.GetString("OPERATIONS_CLIENT_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   External clients remain untrusted until validated by Gateway.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OPERATIONS_CLIENT_NOTES {
            get {
                return ResourceManager.GetString("OPERATIONS_CLIENT_NOTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dedicated routing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OPERATIONS_DEDICATED_AREA {
            get {
                return ResourceManager.GetString("OPERATIONS_DEDICATED_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Routing can attach to channel ownership snapshots next.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OPERATIONS_DEDICATED_NOTES {
            get {
                return ResourceManager.GetString("OPERATIONS_DEDICATED_NOTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Gateway responsibilities and integration points.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OPERATIONS_DESCRIPTION {
            get {
                return ResourceManager.GetString("OPERATIONS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Master link과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OPERATIONS_MASTER_AREA {
            get {
                return ResourceManager.GetString("OPERATIONS_MASTER_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gateway trusts Master only after NodeAccepted.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OPERATIONS_MASTER_NOTES {
            get {
                return ResourceManager.GetString("OPERATIONS_MASTER_NOTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Active과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OPERATIONS_STATE_ACTIVE {
            get {
                return ResourceManager.GetString("OPERATIONS_STATE_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configured과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OPERATIONS_STATE_CONFIGURED {
            get {
                return ResourceManager.GetString("OPERATIONS_STATE_CONFIGURED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pending과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OPERATIONS_STATE_PENDING {
            get {
                return ResourceManager.GetString("OPERATIONS_STATE_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configured과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OPERATIONS_STATUS {
            get {
                return ResourceManager.GetString("OPERATIONS_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Area과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OPERATIONS_TABLE_AREA {
            get {
                return ResourceManager.GetString("OPERATIONS_TABLE_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OPERATIONS_TABLE_NOTES {
            get {
                return ResourceManager.GetString("OPERATIONS_TABLE_NOTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   State과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OPERATIONS_TABLE_STATE {
            get {
                return ResourceManager.GetString("OPERATIONS_TABLE_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gateway Operations과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OPERATIONS_TITLE {
            get {
                return ResourceManager.GetString("OPERATIONS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backend과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TOPBAR_SECTION_BACKEND {
            get {
                return ResourceManager.GetString("TOPBAR_SECTION_BACKEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Balmy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WEATHER_BALMY {
            get {
                return ResourceManager.GetString("WEATHER_BALMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bracing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WEATHER_BRACING {
            get {
                return ResourceManager.GetString("WEATHER_BRACING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chilly과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WEATHER_CHILLY {
            get {
                return ResourceManager.GetString("WEATHER_CHILLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cool과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WEATHER_COOL {
            get {
                return ResourceManager.GetString("WEATHER_COOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Freezing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WEATHER_FREEZING {
            get {
                return ResourceManager.GetString("WEATHER_FREEZING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hot과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WEATHER_HOT {
            get {
                return ResourceManager.GetString("WEATHER_HOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mild과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WEATHER_MILD {
            get {
                return ResourceManager.GetString("WEATHER_MILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scorching과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WEATHER_SCORCHING {
            get {
                return ResourceManager.GetString("WEATHER_SCORCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sweltering과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WEATHER_SWELTERING {
            get {
                return ResourceManager.GetString("WEATHER_SWELTERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WEATHER_WARM {
            get {
                return ResourceManager.GetString("WEATHER_WARM", resourceCulture);
            }
        }
    }
}
