//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordBot.Localizations {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscordBot.Localizations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   DiscordBot과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string APP_TITLE {
            get {
                return ResourceManager.GetString("APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_RELOAD {
            get {
                return ResourceManager.GetString("ERROR_RELOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unhandled error has occurred.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_UNHANDLED {
            get {
                return ResourceManager.GetString("ERROR_UNHANDLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DiscordBot management console과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HOME_SUBTITLE {
            get {
                return ResourceManager.GetString("HOME_SUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HOME_TITLE {
            get {
                return ResourceManager.GetString("HOME_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Welcome, {0}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HOME_WELCOME {
            get {
                return ResourceManager.GetString("HOME_WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NAVMENU_LABEL_HOME {
            get {
                return ResourceManager.GetString("NAVMENU_LABEL_HOME", resourceCulture);
            }
        }

        /// <summary>
        ///   Channels과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NAVMENU_LABEL_CHANNELS {
            get {
                return ResourceManager.GetString("NAVMENU_LABEL_CHANNELS", resourceCulture);
            }
        }

        /// <summary>
        ///   Claude과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NAVMENU_LABEL_CLAUDE_SETTINGS {
            get {
                return ResourceManager.GetString("NAVMENU_LABEL_CLAUDE_SETTINGS", resourceCulture);
            }
        }

        /// <summary>
        ///   Channels과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_TITLE {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_TITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Discord channel settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_SUBTITLE {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_SUBTITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Channel Details과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_DETAIL_TITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Channel settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_DETAIL_SUBTITLE {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_DETAIL_SUBTITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Channel ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_LABEL_CHANNEL_ID {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_LABEL_CHANNEL_ID", resourceCulture);
            }
        }

        /// <summary>
        ///   Guild ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_LABEL_GUILD_ID {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_LABEL_GUILD_ID", resourceCulture);
            }
        }

        /// <summary>
        ///   Channel Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_LABEL_CHANNEL_NAME {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_LABEL_CHANNEL_NAME", resourceCulture);
            }
        }

        /// <summary>
        ///   Guild Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_LABEL_GUILD_NAME {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_LABEL_GUILD_NAME", resourceCulture);
            }
        }

        /// <summary>
        ///   Memo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_LABEL_MEMO {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_LABEL_MEMO", resourceCulture);
            }
        }

        /// <summary>
        ///   Enabled과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_LABEL_ENABLED {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_LABEL_ENABLED", resourceCulture);
            }
        }

        /// <summary>
        ///   Disabled과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_LABEL_DISABLED {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_LABEL_DISABLED", resourceCulture);
            }
        }

        /// <summary>
        ///   Created By과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_LABEL_CREATED_BY {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_LABEL_CREATED_BY", resourceCulture);
            }
        }

        /// <summary>
        ///   Created At과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_LABEL_CREATED_AT {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_LABEL_CREATED_AT", resourceCulture);
            }
        }

        /// <summary>
        ///   Updated At과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_LABEL_UPDATED_AT {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_LABEL_UPDATED_AT", resourceCulture);
            }
        }

        /// <summary>
        ///   Add과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_BUTTON_ADD {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_BUTTON_ADD", resourceCulture);
            }
        }

        /// <summary>
        ///   Details과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_BUTTON_DETAIL {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_BUTTON_DETAIL", resourceCulture);
            }
        }

        /// <summary>
        ///   Back과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_BUTTON_BACK {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_BUTTON_BACK", resourceCulture);
            }
        }

        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_BUTTON_SAVE {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_BUTTON_SAVE", resourceCulture);
            }
        }

        /// <summary>
        ///   Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_BUTTON_DELETE {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_BUTTON_DELETE", resourceCulture);
            }
        }

        /// <summary>
        ///   Loading...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_STATUS_LOADING {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_STATUS_LOADING", resourceCulture);
            }
        }

        /// <summary>
        ///   No channels configured.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_EMPTY {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_EMPTY", resourceCulture);
            }
        }

        /// <summary>
        ///   Channel not found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_STATUS_NOT_FOUND {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_STATUS_NOT_FOUND", resourceCulture);
            }
        }

        /// <summary>
        ///   Channel added.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_STATUS_ADDED {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_STATUS_ADDED", resourceCulture);
            }
        }

        /// <summary>
        ///   Channel saved.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_STATUS_SAVED {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_STATUS_SAVED", resourceCulture);
            }
        }

        /// <summary>
        ///   Channel enabled.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_STATUS_ENABLED {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_STATUS_ENABLED", resourceCulture);
            }
        }

        /// <summary>
        ///   Channel disabled.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_STATUS_DISABLED {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_STATUS_DISABLED", resourceCulture);
            }
        }

        /// <summary>
        ///   Channel deleted.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_STATUS_DELETED {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_STATUS_DELETED", resourceCulture);
            }
        }

        /// <summary>
        ///   Failed to load channels.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_ERROR_LOAD_FAILED {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_ERROR_LOAD_FAILED", resourceCulture);
            }
        }

        /// <summary>
        ///   Failed to save channel.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_ERROR_SAVE_FAILED {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_ERROR_SAVE_FAILED", resourceCulture);
            }
        }

        /// <summary>
        ///   Failed to update channel.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_ERROR_ACTION_FAILED {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_ERROR_ACTION_FAILED", resourceCulture);
            }
        }

        /// <summary>
        ///   Channel ID is required.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLOWED_CHANNELS_ERROR_CHANNEL_ID_REQUIRED {
            get {
                return ResourceManager.GetString("ALLOWED_CHANNELS_ERROR_CHANNEL_ID_REQUIRED", resourceCulture);
            }
        }

        /// <summary>
        ///   Claude Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLAUDE_SETTINGS_TITLE {
            get {
                return ResourceManager.GetString("CLAUDE_SETTINGS_TITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Runtime model configuration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLAUDE_SETTINGS_SUBTITLE {
            get {
                return ResourceManager.GetString("CLAUDE_SETTINGS_SUBTITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Model과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLAUDE_SETTINGS_LABEL_MODEL {
            get {
                return ResourceManager.GetString("CLAUDE_SETTINGS_LABEL_MODEL", resourceCulture);
            }
        }

        /// <summary>
        ///   Summary Model과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLAUDE_SETTINGS_LABEL_SUMMARY_MODEL {
            get {
                return ResourceManager.GetString("CLAUDE_SETTINGS_LABEL_SUMMARY_MODEL", resourceCulture);
            }
        }

        /// <summary>
        ///   Default Max Tokens과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLAUDE_SETTINGS_LABEL_DEFAULT_MAX_TOKENS {
            get {
                return ResourceManager.GetString("CLAUDE_SETTINGS_LABEL_DEFAULT_MAX_TOKENS", resourceCulture);
            }
        }

        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLAUDE_SETTINGS_BUTTON_SAVE {
            get {
                return ResourceManager.GetString("CLAUDE_SETTINGS_BUTTON_SAVE", resourceCulture);
            }
        }

        /// <summary>
        ///   Loading...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLAUDE_SETTINGS_STATUS_LOADING {
            get {
                return ResourceManager.GetString("CLAUDE_SETTINGS_STATUS_LOADING", resourceCulture);
            }
        }

        /// <summary>
        ///   Claude settings saved.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLAUDE_SETTINGS_STATUS_SAVED {
            get {
                return ResourceManager.GetString("CLAUDE_SETTINGS_STATUS_SAVED", resourceCulture);
            }
        }

        /// <summary>
        ///   Failed to load Claude settings.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLAUDE_SETTINGS_ERROR_LOAD_FAILED {
            get {
                return ResourceManager.GetString("CLAUDE_SETTINGS_ERROR_LOAD_FAILED", resourceCulture);
            }
        }

        /// <summary>
        ///   Failed to save Claude settings.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLAUDE_SETTINGS_ERROR_SAVE_FAILED {
            get {
                return ResourceManager.GetString("CLAUDE_SETTINGS_ERROR_SAVE_FAILED", resourceCulture);
            }
        }

        /// <summary>
        ///   Model is required.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLAUDE_SETTINGS_ERROR_MODEL_REQUIRED {
            get {
                return ResourceManager.GetString("CLAUDE_SETTINGS_ERROR_MODEL_REQUIRED", resourceCulture);
            }
        }

        /// <summary>
        ///   Summary model is required.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLAUDE_SETTINGS_ERROR_SUMMARY_MODEL_REQUIRED {
            get {
                return ResourceManager.GetString("CLAUDE_SETTINGS_ERROR_SUMMARY_MODEL_REQUIRED", resourceCulture);
            }
        }

        /// <summary>
        ///   Default max tokens must be greater than 0.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLAUDE_SETTINGS_ERROR_MAX_TOKENS_RANGE {
            get {
                return ResourceManager.GetString("CLAUDE_SETTINGS_ERROR_MAX_TOKENS_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sorry, the content you are looking for does not exist.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NOTFOUND_DESCRIPTION {
            get {
                return ResourceManager.GetString("NOTFOUND_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Found과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NOTFOUND_TITLE {
            get {
                return ResourceManager.GetString("NOTFOUND_TITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Access Denied과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ACCESS_DENIED_TITLE {
            get {
                return ResourceManager.GetString("ACCESS_DENIED_TITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   You do not have permission to access this page. Administrator privileges are required.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ACCESS_DENIED_DESCRIPTION {
            get {
                return ResourceManager.GetString("ACCESS_DENIED_DESCRIPTION", resourceCulture);
            }
        }

        /// <summary>
        ///   Sign out과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ACCESS_DENIED_BUTTON_LOGOUT {
            get {
                return ResourceManager.GetString("ACCESS_DENIED_BUTTON_LOGOUT", resourceCulture);
            }
        }
    }
}
