//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated for strongly typed resource access.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace NoraeBook.Localizations
{
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings
    {
        private static global::System.Resources.ResourceManager? resourceMan;

        private static global::System.Globalization.CultureInfo? resourceCulture;

        internal Strings()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                resourceMan ??= new global::System.Resources.ResourceManager("NoraeBook.Localizations.Strings", typeof(Strings).Assembly);
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo? Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        internal static string APP_TITLE => ResourceManager.GetString("APP_TITLE", resourceCulture)!;

        internal static string AUTH_LOGIN => ResourceManager.GetString("AUTH_LOGIN", resourceCulture)!;

        internal static string AUTH_LOGOUT => ResourceManager.GetString("AUTH_LOGOUT", resourceCulture)!;

        internal static string ERROR_PAGE_MESSAGE => ResourceManager.GetString("ERROR_PAGE_MESSAGE", resourceCulture)!;

        internal static string ERROR_PAGE_TITLE => ResourceManager.GetString("ERROR_PAGE_TITLE", resourceCulture)!;

        internal static string ERROR_RELOAD => ResourceManager.GetString("ERROR_RELOAD", resourceCulture)!;

        internal static string ERROR_REQUEST_ID => ResourceManager.GetString("ERROR_REQUEST_ID", resourceCulture)!;

        internal static string ERROR_UNHANDLED => ResourceManager.GetString("ERROR_UNHANDLED", resourceCulture)!;

        internal static string HOME_EMPTY_DESCRIPTION => ResourceManager.GetString("HOME_EMPTY_DESCRIPTION", resourceCulture)!;

        internal static string HOME_EMPTY_TITLE => ResourceManager.GetString("HOME_EMPTY_TITLE", resourceCulture)!;

        internal static string HOME_EYEBROW => ResourceManager.GetString("HOME_EYEBROW", resourceCulture)!;

        internal static string HOME_NEXT_AUTH => ResourceManager.GetString("HOME_NEXT_AUTH", resourceCulture)!;

        internal static string HOME_NEXT_PLAYLISTS => ResourceManager.GetString("HOME_NEXT_PLAYLISTS", resourceCulture)!;

        internal static string HOME_NEXT_STORAGE => ResourceManager.GetString("HOME_NEXT_STORAGE", resourceCulture)!;

        internal static string HOME_NEXT_TITLE => ResourceManager.GetString("HOME_NEXT_TITLE", resourceCulture)!;

        internal static string HOME_QUEUE_DESCRIPTION => ResourceManager.GetString("HOME_QUEUE_DESCRIPTION", resourceCulture)!;

        internal static string HOME_QUEUE_TITLE => ResourceManager.GetString("HOME_QUEUE_TITLE", resourceCulture)!;

        internal static string HOME_SUMMARY => ResourceManager.GetString("HOME_SUMMARY", resourceCulture)!;

        internal static string HOME_TITLE => ResourceManager.GetString("HOME_TITLE", resourceCulture)!;

        internal static string HOME_WORKSPACE_ARIA => ResourceManager.GetString("HOME_WORKSPACE_ARIA", resourceCulture)!;

        internal static string NOTFOUND_DESCRIPTION => ResourceManager.GetString("NOTFOUND_DESCRIPTION", resourceCulture)!;

        internal static string NOTFOUND_TITLE => ResourceManager.GetString("NOTFOUND_TITLE", resourceCulture)!;

        internal static string STATUS_PLANNED => ResourceManager.GetString("STATUS_PLANNED", resourceCulture)!;
    }
}
