//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated for strongly typed resource access.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace NoraeBook.Localizations
{
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings
    {
        private static global::System.Resources.ResourceManager? resourceMan;

        private static global::System.Globalization.CultureInfo? resourceCulture;

        internal Strings()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                resourceMan ??= new global::System.Resources.ResourceManager("NoraeBook.Localizations.Strings", typeof(Strings).Assembly);
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo? Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        internal static string APP_TITLE => ResourceManager.GetString("APP_TITLE", resourceCulture)!;

        internal static string AUTH_LOGIN => ResourceManager.GetString("AUTH_LOGIN", resourceCulture)!;

        internal static string AUTH_LOGOUT => ResourceManager.GetString("AUTH_LOGOUT", resourceCulture)!;

        internal static string AUTH_REQUIRED_DESCRIPTION => ResourceManager.GetString("AUTH_REQUIRED_DESCRIPTION", resourceCulture)!;

        internal static string AUTH_REQUIRED_TITLE => ResourceManager.GetString("AUTH_REQUIRED_TITLE", resourceCulture)!;

        internal static string ERROR_PAGE_MESSAGE => ResourceManager.GetString("ERROR_PAGE_MESSAGE", resourceCulture)!;

        internal static string ERROR_PAGE_TITLE => ResourceManager.GetString("ERROR_PAGE_TITLE", resourceCulture)!;

        internal static string ERROR_RELOAD => ResourceManager.GetString("ERROR_RELOAD", resourceCulture)!;

        internal static string ERROR_REQUEST_ID => ResourceManager.GetString("ERROR_REQUEST_ID", resourceCulture)!;

        internal static string ERROR_UNHANDLED => ResourceManager.GetString("ERROR_UNHANDLED", resourceCulture)!;

        internal static string HOME_EMPTY_DESCRIPTION => ResourceManager.GetString("HOME_EMPTY_DESCRIPTION", resourceCulture)!;

        internal static string HOME_EMPTY_TITLE => ResourceManager.GetString("HOME_EMPTY_TITLE", resourceCulture)!;

        internal static string HOME_EYEBROW => ResourceManager.GetString("HOME_EYEBROW", resourceCulture)!;

        internal static string HOME_QUEUE_DESCRIPTION => ResourceManager.GetString("HOME_QUEUE_DESCRIPTION", resourceCulture)!;

        internal static string HOME_QUEUE_TITLE => ResourceManager.GetString("HOME_QUEUE_TITLE", resourceCulture)!;

        internal static string HOME_TITLE => ResourceManager.GetString("HOME_TITLE", resourceCulture)!;

        internal static string HOME_WORKSPACE_ARIA => ResourceManager.GetString("HOME_WORKSPACE_ARIA", resourceCulture)!;

        internal static string NOTFOUND_DESCRIPTION => ResourceManager.GetString("NOTFOUND_DESCRIPTION", resourceCulture)!;

        internal static string NOTFOUND_TITLE => ResourceManager.GetString("NOTFOUND_TITLE", resourceCulture)!;

        internal static string SONG_ARTIST_LABEL => ResourceManager.GetString("SONG_ARTIST_LABEL", resourceCulture)!;

        internal static string SONG_CANCEL_BUTTON => ResourceManager.GetString("SONG_CANCEL_BUTTON", resourceCulture)!;

        internal static string SONG_COUNT_FORMAT => ResourceManager.GetString("SONG_COUNT_FORMAT", resourceCulture)!;

        internal static string SONG_CUSTOM_TAGS_LABEL => ResourceManager.GetString("SONG_CUSTOM_TAGS_LABEL", resourceCulture)!;

        internal static string SONG_CUSTOM_TAGS_PLACEHOLDER => ResourceManager.GetString("SONG_CUSTOM_TAGS_PLACEHOLDER", resourceCulture)!;

        internal static string SONG_DELETE_BUTTON => ResourceManager.GetString("SONG_DELETE_BUTTON", resourceCulture)!;

        internal static string SONG_FILTER_ADD_GROUP => ResourceManager.GetString("SONG_FILTER_ADD_GROUP", resourceCulture)!;

        internal static string SONG_FILTER_ARIA => ResourceManager.GetString("SONG_FILTER_ARIA", resourceCulture)!;

        internal static string SONG_FILTER_CLEAR => ResourceManager.GetString("SONG_FILTER_CLEAR", resourceCulture)!;

        internal static string SONG_FILTER_EMPTY_DESCRIPTION => ResourceManager.GetString("SONG_FILTER_EMPTY_DESCRIPTION", resourceCulture)!;

        internal static string SONG_FILTER_EMPTY_TITLE => ResourceManager.GetString("SONG_FILTER_EMPTY_TITLE", resourceCulture)!;

        internal static string SONG_FILTER_GROUP_REMOVE => ResourceManager.GetString("SONG_FILTER_GROUP_REMOVE", resourceCulture)!;

        internal static string SONG_FILTER_GROUP_TITLE_FORMAT => ResourceManager.GetString("SONG_FILTER_GROUP_TITLE_FORMAT", resourceCulture)!;

        internal static string SONG_FILTER_MODE_AND => ResourceManager.GetString("SONG_FILTER_MODE_AND", resourceCulture)!;

        internal static string SONG_FILTER_MODE_ARIA => ResourceManager.GetString("SONG_FILTER_MODE_ARIA", resourceCulture)!;

        internal static string SONG_FILTER_MODE_OR => ResourceManager.GetString("SONG_FILTER_MODE_OR", resourceCulture)!;

        internal static string SONG_FILTER_TITLE => ResourceManager.GetString("SONG_FILTER_TITLE", resourceCulture)!;

        internal static string SONG_FILTERED_COUNT_FORMAT => ResourceManager.GetString("SONG_FILTERED_COUNT_FORMAT", resourceCulture)!;

        internal static string SONG_EDIT_BUTTON => ResourceManager.GetString("SONG_EDIT_BUTTON", resourceCulture)!;

        internal static string SONG_LOADING_DESCRIPTION => ResourceManager.GetString("SONG_LOADING_DESCRIPTION", resourceCulture)!;

        internal static string SONG_LOADING_TITLE => ResourceManager.GetString("SONG_LOADING_TITLE", resourceCulture)!;

        internal static string SONG_NUMBER_LABEL => ResourceManager.GetString("SONG_NUMBER_LABEL", resourceCulture)!;

        internal static string SONG_SAVED_TAG_PRESETS_LABEL => ResourceManager.GetString("SONG_SAVED_TAG_PRESETS_LABEL", resourceCulture)!;

        internal static string SONG_SAVE_BUTTON => ResourceManager.GetString("SONG_SAVE_BUTTON", resourceCulture)!;

        internal static string SONG_TABLE_ACTIONS => ResourceManager.GetString("SONG_TABLE_ACTIONS", resourceCulture)!;

        internal static string SONG_TABLE_ARTIST => ResourceManager.GetString("SONG_TABLE_ARTIST", resourceCulture)!;

        internal static string SONG_TABLE_NUMBER => ResourceManager.GetString("SONG_TABLE_NUMBER", resourceCulture)!;

        internal static string SONG_TABLE_TAGS => ResourceManager.GetString("SONG_TABLE_TAGS", resourceCulture)!;

        internal static string SONG_TABLE_TITLE => ResourceManager.GetString("SONG_TABLE_TITLE", resourceCulture)!;

        internal static string SONG_TAG_FEMALE => ResourceManager.GetString("SONG_TAG_FEMALE", resourceCulture)!;

        internal static string SONG_TAG_MALE => ResourceManager.GetString("SONG_TAG_MALE", resourceCulture)!;

        internal static string SONG_TAG_MIXED => ResourceManager.GetString("SONG_TAG_MIXED", resourceCulture)!;

        internal static string SONG_TAGS_LABEL => ResourceManager.GetString("SONG_TAGS_LABEL", resourceCulture)!;

        internal static string SONG_TITLE_LABEL => ResourceManager.GetString("SONG_TITLE_LABEL", resourceCulture)!;

        internal static string SONG_UPDATE_BUTTON => ResourceManager.GetString("SONG_UPDATE_BUTTON", resourceCulture)!;

        internal static string SONG_VALIDATION_ARTIST => ResourceManager.GetString("SONG_VALIDATION_ARTIST", resourceCulture)!;

        internal static string SONG_VALIDATION_AUTH_REQUIRED => ResourceManager.GetString("SONG_VALIDATION_AUTH_REQUIRED", resourceCulture)!;

        internal static string SONG_VALIDATION_NUMBER => ResourceManager.GetString("SONG_VALIDATION_NUMBER", resourceCulture)!;

        internal static string SONG_VALIDATION_TITLE => ResourceManager.GetString("SONG_VALIDATION_TITLE", resourceCulture)!;

    }
}
