//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated for strongly typed resource access.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SecretGate.Localizations;

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Resources;

[GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
[DebuggerNonUserCode]
internal class Strings
{
    private static ResourceManager? s_ResourceManager;
    private static CultureInfo? s_ResourceCulture;

    internal Strings()
    {
    }

    [EditorBrowsable(EditorBrowsableState.Advanced)]
    internal static ResourceManager ResourceManager
    {
        get
        {
            s_ResourceManager ??= new ResourceManager("SecretGate.Localizations.Strings", typeof(Strings).Assembly);
            return s_ResourceManager;
        }
    }

    [EditorBrowsable(EditorBrowsableState.Advanced)]
    internal static CultureInfo? Culture
    {
        get => s_ResourceCulture;
        set => s_ResourceCulture = value;
    }

    internal static string ADD_SECRET_BUTTON => GetString(nameof(ADD_SECRET_BUTTON));
    internal static string APP_TITLE => GetString(nameof(APP_TITLE));
    internal static string COPY_BUTTON => GetString(nameof(COPY_BUTTON));
    internal static string CREATE_SHARE_BUTTON => GetString(nameof(CREATE_SHARE_BUTTON));
    internal static string DECRYPT_FAILED => GetString(nameof(DECRYPT_FAILED));
    internal static string DELETE_BUTTON => GetString(nameof(DELETE_BUTTON));
    internal static string EMPTY_VAULT => GetString(nameof(EMPTY_VAULT));
    internal static string ERROR_RELOAD => GetString(nameof(ERROR_RELOAD));
    internal static string ERROR_TITLE => GetString(nameof(ERROR_TITLE));
    internal static string ERROR_UNHANDLED => GetString(nameof(ERROR_UNHANDLED));
    internal static string HOME_TITLE => GetString(nameof(HOME_TITLE));
    internal static string LOADING => GetString(nameof(LOADING));
    internal static string LOCK_BUTTON => GetString(nameof(LOCK_BUTTON));
    internal static string LOCKED_SECRET => GetString(nameof(LOCKED_SECRET));
    internal static string MESSAGE_ACCESS_KEY_REQUIRED => GetString(nameof(MESSAGE_ACCESS_KEY_REQUIRED));
    internal static string MESSAGE_INVALID_SUBJECT => GetString(nameof(MESSAGE_INVALID_SUBJECT));
    internal static string MESSAGE_SECRET_DELETED => GetString(nameof(MESSAGE_SECRET_DELETED));
    internal static string MESSAGE_SECRET_REQUIRED => GetString(nameof(MESSAGE_SECRET_REQUIRED));
    internal static string MESSAGE_SECRET_SAVED => GetString(nameof(MESSAGE_SECRET_SAVED));
    internal static string MESSAGE_SHARE_CREATED => GetString(nameof(MESSAGE_SHARE_CREATED));
    internal static string MESSAGE_SHARE_SECRET_REQUIRED => GetString(nameof(MESSAGE_SHARE_SECRET_REQUIRED));
    internal static string MESSAGE_UNLOCK_REQUIRED => GetString(nameof(MESSAGE_UNLOCK_REQUIRED));
    internal static string MESSAGE_VAULT_KEY_REQUIRED => GetString(nameof(MESSAGE_VAULT_KEY_REQUIRED));
    internal static string MESSAGE_VAULT_LOCKED => GetString(nameof(MESSAGE_VAULT_LOCKED));
    internal static string MESSAGE_VAULT_UNLOCKED => GetString(nameof(MESSAGE_VAULT_UNLOCKED));
    internal static string NAV_HOME => GetString(nameof(NAV_HOME));
    internal static string NAV_LOGOUT => GetString(nameof(NAV_LOGOUT));
    internal static string NOT_FOUND_TITLE => GetString(nameof(NOT_FOUND_TITLE));
    internal static string OPEN_SHARE_BUTTON => GetString(nameof(OPEN_SHARE_BUTTON));
    internal static string SECRET_NAME_LABEL => GetString(nameof(SECRET_NAME_LABEL));
    internal static string SECRET_VALUE_LABEL => GetString(nameof(SECRET_VALUE_LABEL));
    internal static string SHARE_ACCESS_KEY_INPUT_LABEL => GetString(nameof(SHARE_ACCESS_KEY_INPUT_LABEL));
    internal static string SHARE_ACCESS_KEY_LABEL => GetString(nameof(SHARE_ACCESS_KEY_LABEL));
    internal static string SHARE_CONSUMED => GetString(nameof(SHARE_CONSUMED));
    internal static string SHARE_EXPIRED_OR_INVALID => GetString(nameof(SHARE_EXPIRED_OR_INVALID));
    internal static string SHARE_EXPIRY_LABEL => GetString(nameof(SHARE_EXPIRY_LABEL));
    internal static string SHARE_LINK_LABEL => GetString(nameof(SHARE_LINK_LABEL));
    internal static string SHARE_PAGE_TITLE => GetString(nameof(SHARE_PAGE_TITLE));
    internal static string SHARE_SECRET_LABEL => GetString(nameof(SHARE_SECRET_LABEL));
    internal static string SHARE_SECRET_RESULT_LABEL => GetString(nameof(SHARE_SECRET_RESULT_LABEL));
    internal static string SHARE_TITLE => GetString(nameof(SHARE_TITLE));
    internal static string SHARE_TOKEN_MISSING => GetString(nameof(SHARE_TOKEN_MISSING));
    internal static string STATUS_LOCKED => GetString(nameof(STATUS_LOCKED));
    internal static string STATUS_UNLOCKED => GetString(nameof(STATUS_UNLOCKED));
    internal static string STORED_SECRETS_TITLE => GetString(nameof(STORED_SECRETS_TITLE));
    internal static string UNLOCK_BUTTON => GetString(nameof(UNLOCK_BUTTON));
    internal static string UPDATED_AT => GetString(nameof(UPDATED_AT));
    internal static string VAULT_KEY_LABEL => GetString(nameof(VAULT_KEY_LABEL));
    internal static string VAULT_TITLE => GetString(nameof(VAULT_TITLE));

    private static string GetString(string name)
    {
        return ResourceManager.GetString(name, s_ResourceCulture) ?? name;
    }
}
