<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
	<LangVersion>13.0</LangVersion>
	<Configurations>Debug;Release;Scripting</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Scripting'">
    <DefineConstants>$(DefineConstants);SCRIPTING</DefineConstants>
  </PropertyGroup>

  <ItemGroup Condition="'$(Configuration)'!='Scripting'">
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="9.0.7" />
  </ItemGroup>

</Project>
