//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     To add or remove a member, edit the .resx file and regenerate this file.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPay.Localizations
{
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() { }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    resourceMan = new global::System.Resources.ResourceManager("NPay.Localizations.Strings", typeof(Strings).Assembly);
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static string APP_TITLE => ResourceManager.GetString("APP_TITLE", resourceCulture)!;
        internal static string BUTTON_CONFIRM => ResourceManager.GetString("BUTTON_CONFIRM", resourceCulture)!;
        internal static string BUTTON_CANCEL => ResourceManager.GetString("BUTTON_CANCEL", resourceCulture)!;
        internal static string BUTTON_DELETE => ResourceManager.GetString("BUTTON_DELETE", resourceCulture)!;
        internal static string BUTTON_EDIT => ResourceManager.GetString("BUTTON_EDIT", resourceCulture)!;
        internal static string BUTTON_LOGIN => ResourceManager.GetString("BUTTON_LOGIN", resourceCulture)!;
        internal static string BUTTON_ADD => ResourceManager.GetString("BUTTON_ADD", resourceCulture)!;
        internal static string BUTTON_CLOSE => ResourceManager.GetString("BUTTON_CLOSE", resourceCulture)!;
        internal static string LOADING => ResourceManager.GetString("LOADING", resourceCulture)!;
        internal static string ERROR_RELOAD => ResourceManager.GetString("ERROR_RELOAD", resourceCulture)!;
        internal static string ERROR_UNHANDLED => ResourceManager.GetString("ERROR_UNHANDLED", resourceCulture)!;

        internal static string NAVMENU_LABEL_HOME => ResourceManager.GetString("NAVMENU_LABEL_HOME", resourceCulture)!;
        internal static string NAVMENU_LABEL_SETTLEMENTS => ResourceManager.GetString("NAVMENU_LABEL_SETTLEMENTS", resourceCulture)!;

        internal static string HOME_TITLE => ResourceManager.GetString("HOME_TITLE", resourceCulture)!;
        internal static string HOME_SUBTITLE => ResourceManager.GetString("HOME_SUBTITLE", resourceCulture)!;
        internal static string HOME_CARD_SETTLEMENTS_TITLE => ResourceManager.GetString("HOME_CARD_SETTLEMENTS_TITLE", resourceCulture)!;
        internal static string HOME_CARD_SETTLEMENTS_DESC => ResourceManager.GetString("HOME_CARD_SETTLEMENTS_DESC", resourceCulture)!;
        internal static string HOME_CARD_SETTLEMENTS_BUTTON => ResourceManager.GetString("HOME_CARD_SETTLEMENTS_BUTTON", resourceCulture)!;
        internal static string HOME_CARD_CREATE_TITLE => ResourceManager.GetString("HOME_CARD_CREATE_TITLE", resourceCulture)!;
        internal static string HOME_CARD_CREATE_DESC => ResourceManager.GetString("HOME_CARD_CREATE_DESC", resourceCulture)!;
        internal static string HOME_CARD_CREATE_BUTTON => ResourceManager.GetString("HOME_CARD_CREATE_BUTTON", resourceCulture)!;

        internal static string SETTLEMENTS_TITLE => ResourceManager.GetString("SETTLEMENTS_TITLE", resourceCulture)!;
        internal static string SETTLEMENTS_SUBTITLE => ResourceManager.GetString("SETTLEMENTS_SUBTITLE", resourceCulture)!;
        internal static string SETTLEMENTS_BUTTON_NEW => ResourceManager.GetString("SETTLEMENTS_BUTTON_NEW", resourceCulture)!;
        internal static string SETTLEMENTS_EMPTY => ResourceManager.GetString("SETTLEMENTS_EMPTY", resourceCulture)!;
        internal static string SETTLEMENTS_COL_TITLE => ResourceManager.GetString("SETTLEMENTS_COL_TITLE", resourceCulture)!;
        internal static string SETTLEMENTS_COL_STATUS => ResourceManager.GetString("SETTLEMENTS_COL_STATUS", resourceCulture)!;
        internal static string SETTLEMENTS_COL_CREATED => ResourceManager.GetString("SETTLEMENTS_COL_CREATED", resourceCulture)!;
        internal static string SETTLEMENTS_COL_PARTICIPANTS => ResourceManager.GetString("SETTLEMENTS_COL_PARTICIPANTS", resourceCulture)!;
        internal static string SETTLEMENTS_COL_ACTIONS => ResourceManager.GetString("SETTLEMENTS_COL_ACTIONS", resourceCulture)!;
        internal static string SETTLEMENTS_STATUS_OPEN => ResourceManager.GetString("SETTLEMENTS_STATUS_OPEN", resourceCulture)!;
        internal static string SETTLEMENTS_STATUS_CLOSED => ResourceManager.GetString("SETTLEMENTS_STATUS_CLOSED", resourceCulture)!;
        internal static string SETTLEMENTS_BUTTON_OPEN => ResourceManager.GetString("SETTLEMENTS_BUTTON_OPEN", resourceCulture)!;
        internal static string SETTLEMENTS_BUTTON_DELETE => ResourceManager.GetString("SETTLEMENTS_BUTTON_DELETE", resourceCulture)!;

        internal static string CREATE_SETTLEMENT_TITLE => ResourceManager.GetString("CREATE_SETTLEMENT_TITLE", resourceCulture)!;
        internal static string CREATE_SETTLEMENT_SUBTITLE => ResourceManager.GetString("CREATE_SETTLEMENT_SUBTITLE", resourceCulture)!;
        internal static string CREATE_SETTLEMENT_LABEL_TITLE => ResourceManager.GetString("CREATE_SETTLEMENT_LABEL_TITLE", resourceCulture)!;
        internal static string CREATE_SETTLEMENT_PLACEHOLDER_TITLE => ResourceManager.GetString("CREATE_SETTLEMENT_PLACEHOLDER_TITLE", resourceCulture)!;
        internal static string CREATE_SETTLEMENT_LABEL_DESC => ResourceManager.GetString("CREATE_SETTLEMENT_LABEL_DESC", resourceCulture)!;
        internal static string CREATE_SETTLEMENT_PLACEHOLDER_DESC => ResourceManager.GetString("CREATE_SETTLEMENT_PLACEHOLDER_DESC", resourceCulture)!;
        internal static string CREATE_SETTLEMENT_BUTTON_CREATE => ResourceManager.GetString("CREATE_SETTLEMENT_BUTTON_CREATE", resourceCulture)!;
        internal static string CREATE_SETTLEMENT_BUTTON_CANCEL => ResourceManager.GetString("CREATE_SETTLEMENT_BUTTON_CANCEL", resourceCulture)!;

        internal static string SETTLEMENT_DETAIL_TAB_EXPENSES => ResourceManager.GetString("SETTLEMENT_DETAIL_TAB_EXPENSES", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_TAB_PARTICIPANTS => ResourceManager.GetString("SETTLEMENT_DETAIL_TAB_PARTICIPANTS", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_TAB_RESULT => ResourceManager.GetString("SETTLEMENT_DETAIL_TAB_RESULT", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_BUTTON_CLOSE => ResourceManager.GetString("SETTLEMENT_DETAIL_BUTTON_CLOSE", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_EXPENSE_LABEL => ResourceManager.GetString("SETTLEMENT_DETAIL_EXPENSE_LABEL", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_EXPENSE_AMOUNT => ResourceManager.GetString("SETTLEMENT_DETAIL_EXPENSE_AMOUNT", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_EXPENSE_PAID_BY => ResourceManager.GetString("SETTLEMENT_DETAIL_EXPENSE_PAID_BY", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_EXPENSE_SPLIT => ResourceManager.GetString("SETTLEMENT_DETAIL_EXPENSE_SPLIT", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_EXPENSE_ADD => ResourceManager.GetString("SETTLEMENT_DETAIL_EXPENSE_ADD", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_EXPENSE_EMPTY => ResourceManager.GetString("SETTLEMENT_DETAIL_EXPENSE_EMPTY", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_PARTICIPANT_NAME => ResourceManager.GetString("SETTLEMENT_DETAIL_PARTICIPANT_NAME", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_PARTICIPANT_ADD => ResourceManager.GetString("SETTLEMENT_DETAIL_PARTICIPANT_ADD", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_PARTICIPANT_EMPTY => ResourceManager.GetString("SETTLEMENT_DETAIL_PARTICIPANT_EMPTY", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_RESULT_EMPTY => ResourceManager.GetString("SETTLEMENT_DETAIL_RESULT_EMPTY", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_RESULT_AI_SUMMARY_TITLE => ResourceManager.GetString("SETTLEMENT_DETAIL_RESULT_AI_SUMMARY_TITLE", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_RESULT_AI_SUMMARY_SUBTITLE => ResourceManager.GetString("SETTLEMENT_DETAIL_RESULT_AI_SUMMARY_SUBTITLE", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_RESULT_AI_SUMMARY_PENDING => ResourceManager.GetString("SETTLEMENT_DETAIL_RESULT_AI_SUMMARY_PENDING", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_RESULT_PAID_SUMMARY_TITLE => ResourceManager.GetString("SETTLEMENT_DETAIL_RESULT_PAID_SUMMARY_TITLE", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_RESULT_PAID_SUMMARY_SUBTITLE => ResourceManager.GetString("SETTLEMENT_DETAIL_RESULT_PAID_SUMMARY_SUBTITLE", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_RESULT_SUMMARY_TITLE => ResourceManager.GetString("SETTLEMENT_DETAIL_RESULT_SUMMARY_TITLE", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_RESULT_SUMMARY_SUBTITLE => ResourceManager.GetString("SETTLEMENT_DETAIL_RESULT_SUMMARY_SUBTITLE", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_RESULT_PAYS => ResourceManager.GetString("SETTLEMENT_DETAIL_RESULT_PAYS", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_RESULT_TO => ResourceManager.GetString("SETTLEMENT_DETAIL_RESULT_TO", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_NOT_FOUND => ResourceManager.GetString("SETTLEMENT_DETAIL_NOT_FOUND", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_EXPENSE_SPLIT_ALL_WARNING => ResourceManager.GetString("SETTLEMENT_DETAIL_EXPENSE_SPLIT_ALL_WARNING", resourceCulture)!;

        internal static string CREATE_SETTLEMENT_LABEL_GUEST_EDIT => ResourceManager.GetString("CREATE_SETTLEMENT_LABEL_GUEST_EDIT", resourceCulture)!;
        internal static string CREATE_SETTLEMENT_HINT_GUEST_EDIT => ResourceManager.GetString("CREATE_SETTLEMENT_HINT_GUEST_EDIT", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_GUEST_EDIT_TOGGLE => ResourceManager.GetString("SETTLEMENT_DETAIL_GUEST_EDIT_TOGGLE", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_GUEST_EDIT_HINT_ON => ResourceManager.GetString("SETTLEMENT_DETAIL_GUEST_EDIT_HINT_ON", resourceCulture)!;
        internal static string SETTLEMENT_DETAIL_GUEST_EDIT_HINT_OFF => ResourceManager.GetString("SETTLEMENT_DETAIL_GUEST_EDIT_HINT_OFF", resourceCulture)!;
    }
}
