//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenAI.Localizations {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenAI.Localizations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AI Chat과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string APP_TITLE {
            get {
                return ResourceManager.GetString("APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AI can make mistakes. Please verify important information yourself.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CHAT_INPUT_HINT {
            get {
                return ResourceManager.GetString("CHAT_INPUT_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type a message...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CHAT_INPUT_PLACEHOLDER {
            get {
                return ResourceManager.GetString("CHAT_INPUT_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AI Chat과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CHAT_PAGE_TITLE {
            get {
                return ResourceManager.GetString("CHAT_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CHAT_SEND_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("CHAT_SEND_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start a conversation with the AI connected to Ollama.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CHAT_WELCOME_SUBTITLE {
            get {
                return ResourceManager.GetString("CHAT_WELCOME_SUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How can I help you?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CHAT_WELCOME_TITLE {
            get {
                return ResourceManager.GetString("CHAT_WELCOME_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_RELOAD {
            get {
                return ResourceManager.GetString("ERROR_RELOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unhandled error has occurred.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_UNHANDLED {
            get {
                return ResourceManager.GetString("ERROR_UNHANDLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New chat과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SIDEBAR_DEFAULT_CHAT_TITLE {
            get {
                return ResourceManager.GetString("SIDEBAR_DEFAULT_CHAT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SIDEBAR_HISTORY_RECENT {
            get {
                return ResourceManager.GetString("SIDEBAR_HISTORY_RECENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New chat과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SIDEBAR_NEW_CHAT {
            get {
                return ResourceManager.GetString("SIDEBAR_NEW_CHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New chat과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TOPBAR_DEFAULT_CONVERSATION_TITLE {
            get {
                return ResourceManager.GetString("TOPBAR_DEFAULT_CONVERSATION_TITLE", resourceCulture);
            }
        }
    }
}
