//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated for strongly typed resource access.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace AutomatedWiki.Localizations;

using System.CodeDom.Compiler;
using System.Globalization;
using System.Resources;

[GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
internal class Strings
{
    private static ResourceManager? resourceMan;
    private static CultureInfo? resourceCulture;

    internal Strings()
    {
    }

    internal static ResourceManager ResourceManager =>
        resourceMan ??= new ResourceManager("AutomatedWiki.Localizations.Strings", typeof(Strings).Assembly);

    internal static CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    internal static string ANSWER_DEFAULT => GetString(nameof(ANSWER_DEFAULT));
    internal static string ANSWER_FORMAT => GetString(nameof(ANSWER_FORMAT));
    internal static string ANSWER_LABEL => GetString(nameof(ANSWER_LABEL));
    internal static string APP_TITLE => GetString(nameof(APP_TITLE));
    internal static string ASSISTANT_PANEL_ARIA => GetString(nameof(ASSISTANT_PANEL_ARIA));
    internal static string ASSISTANT_SUMMARY => GetString(nameof(ASSISTANT_SUMMARY));
    internal static string ASSISTANT_TITLE => GetString(nameof(ASSISTANT_TITLE));
    internal static string AUTH_EYEBROW => GetString(nameof(AUTH_EYEBROW));
    internal static string AUTH_LOGIN => GetString(nameof(AUTH_LOGIN));
    internal static string AUTH_LOGIN_BUTTON => GetString(nameof(AUTH_LOGIN_BUTTON));
    internal static string AUTH_REQUIRED_DESCRIPTION => GetString(nameof(AUTH_REQUIRED_DESCRIPTION));
    internal static string AUTH_REQUIRED_TITLE => GetString(nameof(AUTH_REQUIRED_TITLE));
    internal static string CHANGE_PANEL_ARIA => GetString(nameof(CHANGE_PANEL_ARIA));
    internal static string CHANGE_PANEL_TITLE => GetString(nameof(CHANGE_PANEL_TITLE));
    internal static string DOCUMENT_BODY_ARIA => GetString(nameof(DOCUMENT_BODY_ARIA));
    internal static string ERROR_PAGE_MESSAGE => GetString(nameof(ERROR_PAGE_MESSAGE));
    internal static string ERROR_PAGE_TITLE => GetString(nameof(ERROR_PAGE_TITLE));
    internal static string ERROR_RELOAD => GetString(nameof(ERROR_RELOAD));
    internal static string ERROR_REQUEST_ID => GetString(nameof(ERROR_REQUEST_ID));
    internal static string ERROR_UNHANDLED => GetString(nameof(ERROR_UNHANDLED));
    internal static string HOME_WORKSPACE_ARIA => GetString(nameof(HOME_WORKSPACE_ARIA));
    internal static string NOTFOUND_DESCRIPTION => GetString(nameof(NOTFOUND_DESCRIPTION));
    internal static string NOTFOUND_TITLE => GetString(nameof(NOTFOUND_TITLE));
    internal static string PAGE_ASK_BODY_1 => GetString(nameof(PAGE_ASK_BODY_1));
    internal static string PAGE_ASK_BODY_2 => GetString(nameof(PAGE_ASK_BODY_2));
    internal static string PAGE_ASK_CHANGE_1 => GetString(nameof(PAGE_ASK_CHANGE_1));
    internal static string PAGE_ASK_CHANGE_2 => GetString(nameof(PAGE_ASK_CHANGE_2));
    internal static string PAGE_ASK_SECTION => GetString(nameof(PAGE_ASK_SECTION));
    internal static string PAGE_ASK_SUMMARY => GetString(nameof(PAGE_ASK_SUMMARY));
    internal static string PAGE_ASK_TITLE => GetString(nameof(PAGE_ASK_TITLE));
    internal static string PAGE_COUNT_FORMAT => GetString(nameof(PAGE_COUNT_FORMAT));
    internal static string PAGE_INTAKE_BODY_1 => GetString(nameof(PAGE_INTAKE_BODY_1));
    internal static string PAGE_INTAKE_BODY_2 => GetString(nameof(PAGE_INTAKE_BODY_2));
    internal static string PAGE_INTAKE_CHANGE_1 => GetString(nameof(PAGE_INTAKE_CHANGE_1));
    internal static string PAGE_INTAKE_CHANGE_2 => GetString(nameof(PAGE_INTAKE_CHANGE_2));
    internal static string PAGE_INTAKE_SECTION => GetString(nameof(PAGE_INTAKE_SECTION));
    internal static string PAGE_INTAKE_SUMMARY => GetString(nameof(PAGE_INTAKE_SUMMARY));
    internal static string PAGE_INTAKE_TITLE => GetString(nameof(PAGE_INTAKE_TITLE));
    internal static string PAGE_LIST_ARIA => GetString(nameof(PAGE_LIST_ARIA));
    internal static string PAGE_MAP_BODY_1 => GetString(nameof(PAGE_MAP_BODY_1));
    internal static string PAGE_MAP_BODY_2 => GetString(nameof(PAGE_MAP_BODY_2));
    internal static string PAGE_MAP_CHANGE_1 => GetString(nameof(PAGE_MAP_CHANGE_1));
    internal static string PAGE_MAP_CHANGE_2 => GetString(nameof(PAGE_MAP_CHANGE_2));
    internal static string PAGE_MAP_SECTION => GetString(nameof(PAGE_MAP_SECTION));
    internal static string PAGE_MAP_SUMMARY => GetString(nameof(PAGE_MAP_SUMMARY));
    internal static string PAGE_MAP_TITLE => GetString(nameof(PAGE_MAP_TITLE));
    internal static string PAGE_OVERVIEW_BODY_1 => GetString(nameof(PAGE_OVERVIEW_BODY_1));
    internal static string PAGE_OVERVIEW_BODY_2 => GetString(nameof(PAGE_OVERVIEW_BODY_2));
    internal static string PAGE_OVERVIEW_CHANGE_1 => GetString(nameof(PAGE_OVERVIEW_CHANGE_1));
    internal static string PAGE_OVERVIEW_CHANGE_2 => GetString(nameof(PAGE_OVERVIEW_CHANGE_2));
    internal static string PAGE_OVERVIEW_SECTION => GetString(nameof(PAGE_OVERVIEW_SECTION));
    internal static string PAGE_OVERVIEW_SUMMARY => GetString(nameof(PAGE_OVERVIEW_SUMMARY));
    internal static string PAGE_OVERVIEW_TITLE => GetString(nameof(PAGE_OVERVIEW_TITLE));
    internal static string QUESTION_BUTTON => GetString(nameof(QUESTION_BUTTON));
    internal static string QUESTION_LABEL => GetString(nameof(QUESTION_LABEL));
    internal static string QUESTION_PLACEHOLDER => GetString(nameof(QUESTION_PLACEHOLDER));
    internal static string SEARCH_LABEL => GetString(nameof(SEARCH_LABEL));
    internal static string SEARCH_PLACEHOLDER => GetString(nameof(SEARCH_PLACEHOLDER));
    internal static string STATUS_SYNCED => GetString(nameof(STATUS_SYNCED));
    internal static string STATUS_WATCHING => GetString(nameof(STATUS_WATCHING));
    internal static string TOPBAR_SECTION => GetString(nameof(TOPBAR_SECTION));

    private static string GetString(string name)
    {
        return ResourceManager.GetString(name, resourceCulture) ?? name;
    }
}
