//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated for strongly typed resource access.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace UnityRemoteDebug.Localizations;

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Resources;

[GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
[DebuggerNonUserCode]
internal class Strings
{
    private static ResourceManager? m_ResourceManager;
    private static CultureInfo? m_ResourceCulture;

    internal Strings()
    {
    }

    [EditorBrowsable(EditorBrowsableState.Advanced)]
    internal static ResourceManager ResourceManager => m_ResourceManager ??= new ResourceManager(
        "UnityRemoteDebug.Localizations.Strings",
        typeof(Strings).Assembly);

    [EditorBrowsable(EditorBrowsableState.Advanced)]
    internal static CultureInfo? Culture
    {
        get => m_ResourceCulture;
        set => m_ResourceCulture = value;
    }

    internal static string ACCESS_DENIED_DESCRIPTION => GetString(nameof(ACCESS_DENIED_DESCRIPTION));

    internal static string ACCESS_DENIED_TITLE => GetString(nameof(ACCESS_DENIED_TITLE));

    internal static string APP_TITLE => GetString(nameof(APP_TITLE));

    internal static string ERROR_DEVELOPMENT_MODE_DESCRIPTION => GetString(nameof(ERROR_DEVELOPMENT_MODE_DESCRIPTION));

    internal static string ERROR_DEVELOPMENT_MODE_TITLE => GetString(nameof(ERROR_DEVELOPMENT_MODE_TITLE));

    internal static string ERROR_DEVELOPMENT_MODE_WARNING => GetString(nameof(ERROR_DEVELOPMENT_MODE_WARNING));

    internal static string ERROR_PAGE_MESSAGE => GetString(nameof(ERROR_PAGE_MESSAGE));

    internal static string ERROR_PAGE_TITLE => GetString(nameof(ERROR_PAGE_TITLE));

    internal static string ERROR_REQUEST_ID => GetString(nameof(ERROR_REQUEST_ID));

    internal static string HOME_EYEBROW => GetString(nameof(HOME_EYEBROW));

    internal static string HOME_SUMMARY => GetString(nameof(HOME_SUMMARY));

    internal static string HOME_SUMMARY_ARIA => GetString(nameof(HOME_SUMMARY_ARIA));

    internal static string HOME_TITLE => GetString(nameof(HOME_TITLE));

    internal static string METRIC_ACCESS => GetString(nameof(METRIC_ACCESS));

    internal static string METRIC_ACCESS_DETAIL => GetString(nameof(METRIC_ACCESS_DETAIL));

    internal static string METRIC_ACCESS_VALUE => GetString(nameof(METRIC_ACCESS_VALUE));

    internal static string METRIC_AUTHORITY => GetString(nameof(METRIC_AUTHORITY));

    internal static string METRIC_AUTHORITY_DETAIL => GetString(nameof(METRIC_AUTHORITY_DETAIL));

    internal static string METRIC_AUTHORITY_VALUE => GetString(nameof(METRIC_AUTHORITY_VALUE));

    internal static string METRIC_BACKEND => GetString(nameof(METRIC_BACKEND));

    internal static string METRIC_BACKEND_DETAIL => GetString(nameof(METRIC_BACKEND_DETAIL));

    internal static string METRIC_BACKEND_VALUE => GetString(nameof(METRIC_BACKEND_VALUE));

    internal static string NAV_OVERVIEW => GetString(nameof(NAV_OVERVIEW));

    internal static string NAV_TOGGLE_TITLE => GetString(nameof(NAV_TOGGLE_TITLE));

    internal static string NOTFOUND_DESCRIPTION => GetString(nameof(NOTFOUND_DESCRIPTION));

    internal static string NOTFOUND_TITLE => GetString(nameof(NOTFOUND_TITLE));

    internal static string PANEL_DESCRIPTION => GetString(nameof(PANEL_DESCRIPTION));

    internal static string PANEL_NEXT_ITEM_DEVICE => GetString(nameof(PANEL_NEXT_ITEM_DEVICE));

    internal static string PANEL_NEXT_ITEM_LOGS => GetString(nameof(PANEL_NEXT_ITEM_LOGS));

    internal static string PANEL_NEXT_ITEM_SESSION => GetString(nameof(PANEL_NEXT_ITEM_SESSION));

    internal static string PANEL_NEXT_TITLE => GetString(nameof(PANEL_NEXT_TITLE));

    internal static string PANEL_SCOPE_DETAIL => GetString(nameof(PANEL_SCOPE_DETAIL));

    internal static string PANEL_SCOPE_LABEL => GetString(nameof(PANEL_SCOPE_LABEL));

    internal static string PANEL_SCOPE_VALUE => GetString(nameof(PANEL_SCOPE_VALUE));

    internal static string PANEL_STATUS_DETAIL => GetString(nameof(PANEL_STATUS_DETAIL));

    internal static string PANEL_STATUS_LABEL => GetString(nameof(PANEL_STATUS_LABEL));

    internal static string PANEL_STATUS_VALUE => GetString(nameof(PANEL_STATUS_VALUE));

    internal static string PANEL_TITLE => GetString(nameof(PANEL_TITLE));

    internal static string TOPBAR_SECTION_MANAGEMENT => GetString(nameof(TOPBAR_SECTION_MANAGEMENT));

    private static string GetString(string name)
    {
        return ResourceManager.GetString(name, m_ResourceCulture) ?? name;
    }
}
