//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinecraftSidecar.Localizations {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinecraftSidecar.Localizations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Minecraft Sidecar과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string APP_TITLE {
            get {
                return ResourceManager.GetString("APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BUTTON_REFRESH {
            get {
                return ResourceManager.GetString("BUTTON_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CONSOLE_BUTTON_SEND {
            get {
                return ResourceManager.GetString("CONSOLE_BUTTON_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter command...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CONSOLE_INPUT_PLACEHOLDER {
            get {
                return ResourceManager.GetString("CONSOLE_INPUT_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ERROR] Command failed: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CONSOLE_LOG_COMMAND_FAILED {
            get {
                return ResourceManager.GetString("CONSOLE_LOG_COMMAND_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Command executed successfully]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CONSOLE_LOG_COMMAND_SUCCESS {
            get {
                return ResourceManager.GetString("CONSOLE_LOG_COMMAND_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [INFO] Connect to RCON server to send commands과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CONSOLE_LOG_CONNECT_HINT {
            get {
                return ResourceManager.GetString("CONSOLE_LOG_CONNECT_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ERROR] Connection lost. Please reconnect.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CONSOLE_LOG_CONNECTION_LOST {
            get {
                return ResourceManager.GetString("CONSOLE_LOG_CONNECTION_LOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [INFO] Console initialized과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CONSOLE_LOG_INITIALIZED {
            get {
                return ResourceManager.GetString("CONSOLE_LOG_INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CONSOLE_STATUS_CONNECTED {
            get {
                return ResourceManager.GetString("CONSOLE_STATUS_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CONSOLE_STATUS_DISCONNECTED {
            get {
                return ResourceManager.GetString("CONSOLE_STATUS_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server Console과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CONSOLE_TITLE {
            get {
                return ResourceManager.GetString("CONSOLE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Performance History과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DASHBOARD_CARD_PERFORMANCE_HISTORY {
            get {
                return ResourceManager.GetString("DASHBOARD_CARD_PERFORMANCE_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Players Online과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DASHBOARD_CARD_PLAYERS_ONLINE {
            get {
                return ResourceManager.GetString("DASHBOARD_CARD_PLAYERS_ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server Performance과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DASHBOARD_CARD_SERVER_PERFORMANCE {
            get {
                return ResourceManager.GetString("DASHBOARD_CARD_SERVER_PERFORMANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server Status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DASHBOARD_CARD_SERVER_STATUS {
            get {
                return ResourceManager.GetString("DASHBOARD_CARD_SERVER_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last 20 samples (Green: Good, Yellow: Fair, Red: Poor)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DASHBOARD_PERFORMANCE_CAPTION {
            get {
                return ResourceManager.GetString("DASHBOARD_PERFORMANCE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DASHBOARD_STATUS_CHECKING {
            get {
                return ResourceManager.GetString("DASHBOARD_STATUS_CHECKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Running과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DASHBOARD_STATUS_RUNNING {
            get {
                return ResourceManager.GetString("DASHBOARD_STATUS_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stopped과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DASHBOARD_STATUS_STOPPED {
            get {
                return ResourceManager.GetString("DASHBOARD_STATUS_STOPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minecraft Server Management Dashboard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DASHBOARD_SUBTITLE {
            get {
                return ResourceManager.GetString("DASHBOARD_SUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dashboard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DASHBOARD_TITLE {
            get {
                return ResourceManager.GetString("DASHBOARD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while processing your request.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_PAGE_MESSAGE {
            get {
                return ResourceManager.GetString("ERROR_PAGE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_PAGE_TITLE {
            get {
                return ResourceManager.GetString("ERROR_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Permission Denied.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_PERMISSION_DENIED {
            get {
                return ResourceManager.GetString("ERROR_PERMISSION_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please contact an administrator to request &apos;{0}&apos; permission.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_PERMISSION_DENIED_DESCRIPTION {
            get {
                return ResourceManager.GetString("ERROR_PERMISSION_DENIED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_RELOAD {
            get {
                return ResourceManager.GetString("ERROR_RELOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unhandled error has occurred.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_UNHANDLED {
            get {
                return ResourceManager.GetString("ERROR_UNHANDLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOADING {
            get {
                return ResourceManager.GetString("LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dashboard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NAVMENU_LABEL_DASHBOARD {
            get {
                return ResourceManager.GetString("NAVMENU_LABEL_DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Players과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NAVMENU_LABEL_PLAYERS {
            get {
                return ResourceManager.GetString("NAVMENU_LABEL_PLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Terminal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NAVMENU_LABEL_SERVER_CONSOLE {
            get {
                return ResourceManager.GetString("NAVMENU_LABEL_SERVER_CONSOLE", resourceCulture);
            }
        }

        internal static string NAVMENU_LABEL_SERVER_LOG {
            get {
                return ResourceManager.GetString("NAVMENU_LABEL_SERVER_LOG", resourceCulture);
            }
        }

        internal static string SERVERLOG_TITLE {
            get {
                return ResourceManager.GetString("SERVERLOG_TITLE", resourceCulture);
            }
        }

        internal static string SERVERLOG_STATUS_WATCHING {
            get {
                return ResourceManager.GetString("SERVERLOG_STATUS_WATCHING", resourceCulture);
            }
        }

        internal static string SERVERLOG_STATUS_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("SERVERLOG_STATUS_FILE_NOT_FOUND", resourceCulture);
            }
        }

        /// <summary>
        ///   Kick과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PLAYERS_BUTTON_KICK {
            get {
                return ResourceManager.GetString("PLAYERS_BUTTON_KICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No players online과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PLAYERS_EMPTY {
            get {
                return ResourceManager.GetString("PLAYERS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading players...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PLAYERS_LOADING {
            get {
                return ResourceManager.GetString("PLAYERS_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Actions과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PLAYERS_TABLE_ACTIONS {
            get {
                return ResourceManager.GetString("PLAYERS_TABLE_ACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Player Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PLAYERS_TABLE_NAME {
            get {
                return ResourceManager.GetString("PLAYERS_TABLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Online Players과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PLAYERS_TITLE {
            get {
                return ResourceManager.GetString("PLAYERS_TITLE", resourceCulture);
            }
        }
    }
}
