<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>RemoteDebug</RootNamespace>
    <LangVersion>10.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GatewayServer.Abstractions\GatewayServer.Abstractions.csproj" />
    <ProjectReference Include="..\PacketCore\PacketCore.csproj" />
    <ProjectReference Include="..\RemoteDebugServer.Abstractions\RemoteDebugServer.Abstractions.csproj" />
  </ItemGroup>

</Project>
